//! Bulk operations for AgingSnapshot entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAgingSnapshotDto;
use crate::application::service::AgingSnapshotService;
use crate::domain::entity::AgingSnapshot;

/// Bulk operation handler for AgingSnapshot entities.
///
/// Wraps `AgingSnapshotService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AgingSnapshotBulkService = GenericBulkService<AgingSnapshot, CreateAgingSnapshotDto, AgingSnapshotService>;

// <<< CUSTOM
// END CUSTOM
