//! Bulk operations for AgingBucket entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAgingBucketDto;
use crate::application::service::AgingBucketService;
use crate::domain::entity::AgingBucket;

/// Bulk operation handler for AgingBucket entities.
///
/// Wraps `AgingBucketService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AgingBucketBulkService = GenericBulkService<AgingBucket, CreateAgingBucketDto, AgingBucketService>;

// <<< CUSTOM
// END CUSTOM
