//! Bulk operations for DunningAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDunningActionDto;
use crate::application::service::DunningActionService;
use crate::domain::entity::DunningAction;

/// Bulk operation handler for DunningAction entities.
///
/// Wraps `DunningActionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DunningActionBulkService = GenericBulkService<DunningAction, CreateDunningActionDto, DunningActionService>;

// <<< CUSTOM
// END CUSTOM
