//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod mode_of_payment_bulk;
pub mod payment_entry_bulk;
pub mod payment_allocation_bulk;

pub use mode_of_payment_bulk::ModeOfPaymentBulkService;
pub use payment_entry_bulk::PaymentEntryBulkService;
pub use payment_allocation_bulk::PaymentAllocationBulkService;

// <<< CUSTOM
// END CUSTOM
