//! Bulk operations for ModeOfPayment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateModeOfPaymentDto;
use crate::application::service::ModeOfPaymentService;
use crate::domain::entity::ModeOfPayment;

/// Bulk operation handler for ModeOfPayment entities.
///
/// Wraps `ModeOfPaymentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ModeOfPaymentBulkService = GenericBulkService<ModeOfPayment, CreateModeOfPaymentDto, ModeOfPaymentService>;

// <<< CUSTOM
// END CUSTOM
