//! Bulk operations for PaymentAllocation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePaymentAllocationDto;
use crate::application::service::PaymentAllocationService;
use crate::domain::entity::PaymentAllocation;

/// Bulk operation handler for PaymentAllocation entities.
///
/// Wraps `PaymentAllocationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PaymentAllocationBulkService = GenericBulkService<PaymentAllocation, CreatePaymentAllocationDto, PaymentAllocationService>;

// <<< CUSTOM
// END CUSTOM
