//! AgingBucket DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AgingBucket;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AgingBucketName;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AgingBucket
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAgingBucketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "snapshot_id")]
    pub snapshot_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "days_past_due")]
    pub days_past_due: i32,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    pub bucket: AgingBucketName,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AgingBucket
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAgingBucketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "snapshot_id")]
    pub snapshot_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "days_past_due")]
    pub days_past_due: i32,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    pub bucket: AgingBucketName,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AgingBucket
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAgingBucketDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "snapshot_id")]
    pub snapshot_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_ref")]
    pub invoice_ref: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_kind")]
    pub invoice_kind: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "days_past_due")]
    pub days_past_due: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "outstanding_amount")]
    pub outstanding_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bucket: Option<AgingBucketName>,
}

impl PatchAgingBucketDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.snapshot_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.party_id.is_some() || self.due_date.is_some() || self.days_past_due.is_some() || self.outstanding_amount.is_some() || self.bucket.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AgingBucket entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingBucketResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub snapshot_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_kind: String,
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub due_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub days_past_due: i32,
    pub outstanding_amount: Decimal,
    pub bucket: AgingBucketName,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AgingBucket entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingBucketListResponseDto {
    /// List of items
    pub items: Vec<AgingBucketResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AgingBucketListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AgingBucketResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingBucketSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub snapshot_id: Uuid,
    pub invoice_ref: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AgingBucket> for AgingBucketResponseDto {
    fn from(entity: AgingBucket) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            snapshot_id: entity.snapshot_id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            party_id: entity.party_id,
            due_date: entity.due_date,
            days_past_due: entity.days_past_due,
            outstanding_amount: entity.outstanding_amount,
            bucket: entity.bucket,
            metadata: entity.metadata,
        }
    }
}

impl From<AgingBucket> for AgingBucketSummaryDto {
    fn from(entity: AgingBucket) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            snapshot_id: entity.snapshot_id,
            invoice_ref: entity.invoice_ref,
            created_at,
        }
    }
}

impl From<CreateAgingBucketDto> for AgingBucket {
    fn from(dto: CreateAgingBucketDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            snapshot_id: dto.snapshot_id,
            invoice_ref: dto.invoice_ref,
            invoice_kind: dto.invoice_kind,
            party_id: dto.party_id,
            due_date: dto.due_date,
            days_past_due: dto.days_past_due,
            outstanding_amount: dto.outstanding_amount,
            bucket: dto.bucket,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AgingBucket> for AgingBucketResponseDto {
    fn from(entity: &AgingBucket) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            snapshot_id: entity.snapshot_id.clone(),
            invoice_ref: entity.invoice_ref.clone(),
            invoice_kind: entity.invoice_kind.clone(),
            party_id: entity.party_id.clone(),
            due_date: entity.due_date.clone(),
            days_past_due: entity.days_past_due.clone(),
            outstanding_amount: entity.outstanding_amount.clone(),
            bucket: entity.bucket.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAgingBucketDto> for AgingBucket {
    fn from_create_dto(dto: CreateAgingBucketDto) -> backbone_core::ServiceResult<Self> {
        Ok(AgingBucket::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAgingBucketDto> for AgingBucket {
    fn apply_update(mut self, dto: UpdateAgingBucketDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.snapshot_id = dto.snapshot_id;
        self.invoice_ref = dto.invoice_ref;
        self.invoice_kind = dto.invoice_kind;
        self.party_id = dto.party_id;
        self.due_date = dto.due_date;
        self.days_past_due = dto.days_past_due;
        self.outstanding_amount = dto.outstanding_amount;
        self.bucket = dto.bucket;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AgingBucket here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

