//! AgingSnapshot DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AgingSnapshot;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SnapshotStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AgingSnapshot
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAgingSnapshotDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "as_of_date")]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    #[serde(alias = "total_outstanding")]
    pub total_outstanding: Decimal,
    #[serde(alias = "bucket_current")]
    pub bucket_current: Decimal,
    #[serde(alias = "bucket_1_30")]
    pub bucket_1_30: Decimal,
    #[serde(alias = "bucket_31_60")]
    pub bucket_31_60: Decimal,
    #[serde(alias = "bucket_61_90")]
    pub bucket_61_90: Decimal,
    #[serde(alias = "bucket_90p")]
    pub bucket_90p: Decimal,
    pub status: SnapshotStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AgingSnapshot
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAgingSnapshotDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "as_of_date")]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    #[serde(alias = "total_outstanding")]
    pub total_outstanding: Decimal,
    #[serde(alias = "bucket_current")]
    pub bucket_current: Decimal,
    #[serde(alias = "bucket_1_30")]
    pub bucket_1_30: Decimal,
    #[serde(alias = "bucket_31_60")]
    pub bucket_31_60: Decimal,
    #[serde(alias = "bucket_61_90")]
    pub bucket_61_90: Decimal,
    #[serde(alias = "bucket_90p")]
    pub bucket_90p: Decimal,
    pub status: SnapshotStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AgingSnapshot
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAgingSnapshotDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "as_of_date")]
    pub as_of_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_outstanding")]
    pub total_outstanding: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bucket_current")]
    pub bucket_current: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bucket_1_30")]
    pub bucket_1_30: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bucket_31_60")]
    pub bucket_31_60: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bucket_61_90")]
    pub bucket_61_90: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bucket_90p")]
    pub bucket_90p: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SnapshotStatus>,
}

impl PatchAgingSnapshotDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.as_of_date.is_some() || self.direction.is_some() || self.total_outstanding.is_some() || self.bucket_current.is_some() || self.bucket_1_30.is_some() || self.bucket_31_60.is_some() || self.bucket_61_90.is_some() || self.bucket_90p.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AgingSnapshot entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingSnapshotResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    pub total_outstanding: Decimal,
    pub bucket_current: Decimal,
    pub bucket_1_30: Decimal,
    pub bucket_31_60: Decimal,
    pub bucket_61_90: Decimal,
    pub bucket_90p: Decimal,
    pub status: SnapshotStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AgingSnapshot entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingSnapshotListResponseDto {
    /// List of items
    pub items: Vec<AgingSnapshotResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AgingSnapshotListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AgingSnapshotResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AgingSnapshotSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub as_of_date: NaiveDate,
    pub direction: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AgingSnapshot> for AgingSnapshotResponseDto {
    fn from(entity: AgingSnapshot) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            as_of_date: entity.as_of_date,
            direction: entity.direction,
            total_outstanding: entity.total_outstanding,
            bucket_current: entity.bucket_current,
            bucket_1_30: entity.bucket_1_30,
            bucket_31_60: entity.bucket_31_60,
            bucket_61_90: entity.bucket_61_90,
            bucket_90p: entity.bucket_90p,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<AgingSnapshot> for AgingSnapshotSummaryDto {
    fn from(entity: AgingSnapshot) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            as_of_date: entity.as_of_date,
            direction: entity.direction,
            created_at,
        }
    }
}

impl From<CreateAgingSnapshotDto> for AgingSnapshot {
    fn from(dto: CreateAgingSnapshotDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            as_of_date: dto.as_of_date,
            direction: dto.direction,
            total_outstanding: dto.total_outstanding,
            bucket_current: dto.bucket_current,
            bucket_1_30: dto.bucket_1_30,
            bucket_31_60: dto.bucket_31_60,
            bucket_61_90: dto.bucket_61_90,
            bucket_90p: dto.bucket_90p,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AgingSnapshot> for AgingSnapshotResponseDto {
    fn from(entity: &AgingSnapshot) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            as_of_date: entity.as_of_date.clone(),
            direction: entity.direction.clone(),
            total_outstanding: entity.total_outstanding.clone(),
            bucket_current: entity.bucket_current.clone(),
            bucket_1_30: entity.bucket_1_30.clone(),
            bucket_31_60: entity.bucket_31_60.clone(),
            bucket_61_90: entity.bucket_61_90.clone(),
            bucket_90p: entity.bucket_90p.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAgingSnapshotDto> for AgingSnapshot {
    fn from_create_dto(dto: CreateAgingSnapshotDto) -> backbone_core::ServiceResult<Self> {
        Ok(AgingSnapshot::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAgingSnapshotDto> for AgingSnapshot {
    fn apply_update(mut self, dto: UpdateAgingSnapshotDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.as_of_date = dto.as_of_date;
        self.direction = dto.direction;
        self.total_outstanding = dto.total_outstanding;
        self.bucket_current = dto.bucket_current;
        self.bucket_1_30 = dto.bucket_1_30;
        self.bucket_31_60 = dto.bucket_31_60;
        self.bucket_61_90 = dto.bucket_61_90;
        self.bucket_90p = dto.bucket_90p;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AgingSnapshot here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

