//! DunningRun DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DunningRun;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DunningRunStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DunningRun
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDunningRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "as_of_date")]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "snapshot_id")]
    pub snapshot_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "actions_emitted")]
    pub actions_emitted: i32,
    pub status: DunningRunStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DunningRun
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDunningRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "as_of_date")]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "snapshot_id")]
    pub snapshot_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "actions_emitted")]
    pub actions_emitted: i32,
    pub status: DunningRunStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DunningRun
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDunningRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "as_of_date")]
    pub as_of_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "snapshot_id")]
    pub snapshot_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "actions_emitted")]
    pub actions_emitted: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DunningRunStatus>,
}

impl PatchDunningRunDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.as_of_date.is_some() || self.direction.is_some() || self.snapshot_id.is_some() || self.actions_emitted.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DunningRun entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningRunResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub as_of_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub direction: String,
    pub snapshot_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub actions_emitted: i32,
    pub status: DunningRunStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DunningRun entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningRunListResponseDto {
    /// List of items
    pub items: Vec<DunningRunResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DunningRunListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DunningRunResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningRunSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub as_of_date: NaiveDate,
    pub direction: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DunningRun> for DunningRunResponseDto {
    fn from(entity: DunningRun) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            as_of_date: entity.as_of_date,
            direction: entity.direction,
            snapshot_id: entity.snapshot_id,
            actions_emitted: entity.actions_emitted,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<DunningRun> for DunningRunSummaryDto {
    fn from(entity: DunningRun) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            as_of_date: entity.as_of_date,
            direction: entity.direction,
            created_at,
        }
    }
}

impl From<CreateDunningRunDto> for DunningRun {
    fn from(dto: CreateDunningRunDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            as_of_date: dto.as_of_date,
            direction: dto.direction,
            snapshot_id: dto.snapshot_id,
            actions_emitted: dto.actions_emitted,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DunningRun> for DunningRunResponseDto {
    fn from(entity: &DunningRun) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            as_of_date: entity.as_of_date.clone(),
            direction: entity.direction.clone(),
            snapshot_id: entity.snapshot_id.clone(),
            actions_emitted: entity.actions_emitted.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDunningRunDto> for DunningRun {
    fn from_create_dto(dto: CreateDunningRunDto) -> backbone_core::ServiceResult<Self> {
        Ok(DunningRun::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDunningRunDto> for DunningRun {
    fn apply_update(mut self, dto: UpdateDunningRunDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.as_of_date = dto.as_of_date;
        self.direction = dto.direction;
        self.snapshot_id = dto.snapshot_id;
        self.actions_emitted = dto.actions_emitted;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DunningRun here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

