//! DunningAction DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DunningAction;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DunningActionStatus;
use crate::domain::entity::DunningActionType;
use crate::domain::entity::DunningLevel;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DunningAction
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDunningActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "run_id")]
    pub run_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    pub level: DunningLevel,
    #[serde(alias = "action_type")]
    pub action_type: DunningActionType,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "days_past_due")]
    pub days_past_due: i32,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    pub status: DunningActionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "processed_at")]
    pub processed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "result_ref")]
    pub result_ref: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DunningAction
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDunningActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "run_id")]
    pub run_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    pub level: DunningLevel,
    #[serde(alias = "action_type")]
    pub action_type: DunningActionType,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "days_past_due")]
    pub days_past_due: i32,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    pub status: DunningActionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "processed_at")]
    pub processed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "result_ref")]
    pub result_ref: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DunningAction
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDunningActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "run_id")]
    pub run_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_ref")]
    pub invoice_ref: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_kind")]
    pub invoice_kind: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<DunningLevel>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "action_type")]
    pub action_type: Option<DunningActionType>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "days_past_due")]
    pub days_past_due: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "outstanding_amount")]
    pub outstanding_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DunningActionStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "processed_at")]
    pub processed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "result_ref")]
    pub result_ref: Option<String>,
}

impl PatchDunningActionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.run_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.party_id.is_some() || self.level.is_some() || self.action_type.is_some() || self.days_past_due.is_some() || self.outstanding_amount.is_some() || self.status.is_some() || self.processed_at.is_some() || self.result_ref.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DunningAction entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningActionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub run_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoice_ref: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_kind: String,
    pub party_id: Option<Uuid>,
    pub level: DunningLevel,
    pub action_type: DunningActionType,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub days_past_due: i32,
    pub outstanding_amount: Decimal,
    pub status: DunningActionStatus,
    pub processed_at: Option<DateTime<Utc>>,
    pub result_ref: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DunningAction entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningActionListResponseDto {
    /// List of items
    pub items: Vec<DunningActionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DunningActionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DunningActionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DunningActionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub run_id: Uuid,
    pub invoice_ref: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DunningAction> for DunningActionResponseDto {
    fn from(entity: DunningAction) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            run_id: entity.run_id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            party_id: entity.party_id,
            level: entity.level,
            action_type: entity.action_type,
            days_past_due: entity.days_past_due,
            outstanding_amount: entity.outstanding_amount,
            status: entity.status,
            processed_at: entity.processed_at,
            result_ref: entity.result_ref,
            metadata: entity.metadata,
        }
    }
}

impl From<DunningAction> for DunningActionSummaryDto {
    fn from(entity: DunningAction) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            run_id: entity.run_id,
            invoice_ref: entity.invoice_ref,
            created_at,
        }
    }
}

impl From<CreateDunningActionDto> for DunningAction {
    fn from(dto: CreateDunningActionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            run_id: dto.run_id,
            invoice_ref: dto.invoice_ref,
            invoice_kind: dto.invoice_kind,
            party_id: dto.party_id,
            level: dto.level,
            action_type: dto.action_type,
            days_past_due: dto.days_past_due,
            outstanding_amount: dto.outstanding_amount,
            status: dto.status,
            processed_at: dto.processed_at,
            result_ref: dto.result_ref,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DunningAction> for DunningActionResponseDto {
    fn from(entity: &DunningAction) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            run_id: entity.run_id.clone(),
            invoice_ref: entity.invoice_ref.clone(),
            invoice_kind: entity.invoice_kind.clone(),
            party_id: entity.party_id.clone(),
            level: entity.level.clone(),
            action_type: entity.action_type.clone(),
            days_past_due: entity.days_past_due.clone(),
            outstanding_amount: entity.outstanding_amount.clone(),
            status: entity.status.clone(),
            processed_at: entity.processed_at.clone(),
            result_ref: entity.result_ref.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDunningActionDto> for DunningAction {
    fn from_create_dto(dto: CreateDunningActionDto) -> backbone_core::ServiceResult<Self> {
        Ok(DunningAction::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDunningActionDto> for DunningAction {
    fn apply_update(mut self, dto: UpdateDunningActionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.run_id = dto.run_id;
        self.invoice_ref = dto.invoice_ref;
        self.invoice_kind = dto.invoice_kind;
        self.party_id = dto.party_id;
        self.level = dto.level;
        self.action_type = dto.action_type;
        self.days_past_due = dto.days_past_due;
        self.outstanding_amount = dto.outstanding_amount;
        self.status = dto.status;
        self.processed_at = dto.processed_at;
        self.result_ref = dto.result_ref;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DunningAction here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

