//! PaymentEntry DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PaymentEntry;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GlPostingState;
use crate::domain::entity::PaymentPartyType;
use crate::domain::entity::PaymentStatus;
use crate::domain::entity::PaymentType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PaymentEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentEntryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "payment_number")]
    pub payment_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(alias = "payment_type")]
    pub payment_type: PaymentType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<PaymentPartyType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "posting_date")]
    pub posting_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mode_of_payment_id")]
    pub mode_of_payment_id: Option<Uuid>,
    #[serde(alias = "paid_amount")]
    pub paid_amount: Decimal,
    #[serde(alias = "allocated_amount")]
    pub allocated_amount: Decimal,
    #[serde(alias = "unallocated_amount")]
    pub unallocated_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_account_id")]
    pub bank_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_account_id")]
    pub party_account_id: Uuid,
    pub status: PaymentStatus,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PaymentEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentEntryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "payment_number")]
    pub payment_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(alias = "payment_type")]
    pub payment_type: PaymentType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<PaymentPartyType>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "posting_date")]
    pub posting_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mode_of_payment_id")]
    pub mode_of_payment_id: Option<Uuid>,
    #[serde(alias = "paid_amount")]
    pub paid_amount: Decimal,
    #[serde(alias = "allocated_amount")]
    pub allocated_amount: Decimal,
    #[serde(alias = "unallocated_amount")]
    pub unallocated_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_account_id")]
    pub bank_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_account_id")]
    pub party_account_id: Uuid,
    pub status: PaymentStatus,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PaymentEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentEntryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_number")]
    pub payment_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_type")]
    pub payment_type: Option<PaymentType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_type")]
    pub party_type: Option<PaymentPartyType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_date")]
    pub posting_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mode_of_payment_id")]
    pub mode_of_payment_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "paid_amount")]
    pub paid_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "allocated_amount")]
    pub allocated_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unallocated_amount")]
    pub unallocated_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bank_account_id")]
    pub bank_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_account_id")]
    pub party_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PaymentStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_state")]
    pub posting_state: Option<GlPostingState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "reference_no")]
    pub reference_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchPaymentEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.payment_number.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.payment_type.is_some() || self.party_type.is_some() || self.party_id.is_some() || self.posting_date.is_some() || self.currency.is_some() || self.mode_of_payment_id.is_some() || self.paid_amount.is_some() || self.allocated_amount.is_some() || self.unallocated_amount.is_some() || self.bank_account_id.is_some() || self.party_account_id.is_some() || self.status.is_some() || self.posting_state.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.posted_at.is_some() || self.reference_no.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PaymentEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentEntryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payment_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub payment_type: PaymentType,
    pub party_type: Option<PaymentPartyType>,
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub posting_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub mode_of_payment_id: Option<Uuid>,
    pub paid_amount: Decimal,
    pub allocated_amount: Decimal,
    pub unallocated_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bank_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub party_account_id: Uuid,
    pub status: PaymentStatus,
    pub posting_state: GlPostingState,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub posted_at: Option<DateTime<Utc>>,
    pub reference_no: Option<String>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PaymentEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentEntryListResponseDto {
    /// List of items
    pub items: Vec<PaymentEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentEntryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentEntrySummaryDto {
    pub id: Uuid,
    pub payment_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PaymentEntry> for PaymentEntryResponseDto {
    fn from(entity: PaymentEntry) -> Self {
        Self {
            id: entity.id,
            payment_number: entity.payment_number,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            payment_type: entity.payment_type,
            party_type: entity.party_type,
            party_id: entity.party_id,
            posting_date: entity.posting_date,
            currency: entity.currency,
            mode_of_payment_id: entity.mode_of_payment_id,
            paid_amount: entity.paid_amount,
            allocated_amount: entity.allocated_amount,
            unallocated_amount: entity.unallocated_amount,
            bank_account_id: entity.bank_account_id,
            party_account_id: entity.party_account_id,
            status: entity.status,
            posting_state: entity.posting_state,
            journal_id: entity.journal_id,
            accounting_post_id: entity.accounting_post_id,
            posted_at: entity.posted_at,
            reference_no: entity.reference_no,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<PaymentEntry> for PaymentEntrySummaryDto {
    fn from(entity: PaymentEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            payment_number: entity.payment_number,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            created_at,
        }
    }
}

impl From<CreatePaymentEntryDto> for PaymentEntry {
    fn from(dto: CreatePaymentEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            payment_number: dto.payment_number,
            company_id: dto.company_id,
            branch_id: dto.branch_id,
            payment_type: dto.payment_type,
            party_type: dto.party_type,
            party_id: dto.party_id,
            posting_date: dto.posting_date,
            currency: dto.currency,
            mode_of_payment_id: dto.mode_of_payment_id,
            paid_amount: dto.paid_amount,
            allocated_amount: dto.allocated_amount,
            unallocated_amount: dto.unallocated_amount,
            bank_account_id: dto.bank_account_id,
            party_account_id: dto.party_account_id,
            status: dto.status,
            posting_state: dto.posting_state,
            journal_id: dto.journal_id,
            accounting_post_id: dto.accounting_post_id,
            posted_at: dto.posted_at,
            reference_no: dto.reference_no,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PaymentEntry> for PaymentEntryResponseDto {
    fn from(entity: &PaymentEntry) -> Self {
        Self {
            id: entity.id.clone(),
            payment_number: entity.payment_number.clone(),
            company_id: entity.company_id.clone(),
            branch_id: entity.branch_id.clone(),
            payment_type: entity.payment_type.clone(),
            party_type: entity.party_type.clone(),
            party_id: entity.party_id.clone(),
            posting_date: entity.posting_date.clone(),
            currency: entity.currency.clone(),
            mode_of_payment_id: entity.mode_of_payment_id.clone(),
            paid_amount: entity.paid_amount.clone(),
            allocated_amount: entity.allocated_amount.clone(),
            unallocated_amount: entity.unallocated_amount.clone(),
            bank_account_id: entity.bank_account_id.clone(),
            party_account_id: entity.party_account_id.clone(),
            status: entity.status.clone(),
            posting_state: entity.posting_state.clone(),
            journal_id: entity.journal_id.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            posted_at: entity.posted_at.clone(),
            reference_no: entity.reference_no.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentEntryDto> for PaymentEntry {
    fn from_create_dto(dto: CreatePaymentEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(PaymentEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentEntryDto> for PaymentEntry {
    fn apply_update(mut self, dto: UpdatePaymentEntryDto) -> backbone_core::ServiceResult<Self> {
        self.payment_number = dto.payment_number;
        self.company_id = dto.company_id;
        self.branch_id = dto.branch_id;
        self.payment_type = dto.payment_type;
        self.party_type = dto.party_type;
        self.party_id = dto.party_id;
        self.posting_date = dto.posting_date;
        self.currency = dto.currency;
        self.mode_of_payment_id = dto.mode_of_payment_id;
        self.paid_amount = dto.paid_amount;
        self.allocated_amount = dto.allocated_amount;
        self.unallocated_amount = dto.unallocated_amount;
        self.bank_account_id = dto.bank_account_id;
        self.party_account_id = dto.party_account_id;
        self.status = dto.status;
        self.posting_state = dto.posting_state;
        self.journal_id = dto.journal_id;
        self.accounting_post_id = dto.accounting_post_id;
        self.posted_at = dto.posted_at;
        self.reference_no = dto.reference_no;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PaymentEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
