//! PaymentAllocation DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PaymentAllocation;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SettlementKind;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PaymentAllocation
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "payment_id")]
    pub payment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: SettlementKind,
    #[serde(alias = "allocated_amount")]
    pub allocated_amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PaymentAllocation
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "payment_id")]
    pub payment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: SettlementKind,
    #[serde(alias = "allocated_amount")]
    pub allocated_amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PaymentAllocation
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_id")]
    pub payment_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_ref")]
    pub invoice_ref: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_kind")]
    pub invoice_kind: Option<SettlementKind>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "allocated_amount")]
    pub allocated_amount: Option<Decimal>,
}

impl PatchPaymentAllocationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.payment_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.allocated_amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PaymentAllocation entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentAllocationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoice_ref: Uuid,
    pub invoice_kind: SettlementKind,
    pub allocated_amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PaymentAllocation entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentAllocationListResponseDto {
    /// List of items
    pub items: Vec<PaymentAllocationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentAllocationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentAllocationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentAllocationSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub payment_id: Uuid,
    pub invoice_ref: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PaymentAllocation> for PaymentAllocationResponseDto {
    fn from(entity: PaymentAllocation) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            payment_id: entity.payment_id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            allocated_amount: entity.allocated_amount,
            metadata: entity.metadata,
        }
    }
}

impl From<PaymentAllocation> for PaymentAllocationSummaryDto {
    fn from(entity: PaymentAllocation) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            payment_id: entity.payment_id,
            invoice_ref: entity.invoice_ref,
            created_at,
        }
    }
}

impl From<CreatePaymentAllocationDto> for PaymentAllocation {
    fn from(dto: CreatePaymentAllocationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            payment_id: dto.payment_id,
            invoice_ref: dto.invoice_ref,
            invoice_kind: dto.invoice_kind,
            allocated_amount: dto.allocated_amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PaymentAllocation> for PaymentAllocationResponseDto {
    fn from(entity: &PaymentAllocation) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            payment_id: entity.payment_id.clone(),
            invoice_ref: entity.invoice_ref.clone(),
            invoice_kind: entity.invoice_kind.clone(),
            allocated_amount: entity.allocated_amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentAllocationDto> for PaymentAllocation {
    fn from_create_dto(dto: CreatePaymentAllocationDto) -> backbone_core::ServiceResult<Self> {
        Ok(PaymentAllocation::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentAllocationDto> for PaymentAllocation {
    fn apply_update(mut self, dto: UpdatePaymentAllocationDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.payment_id = dto.payment_id;
        self.invoice_ref = dto.invoice_ref;
        self.invoice_kind = dto.invoice_kind;
        self.allocated_amount = dto.allocated_amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PaymentAllocation here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
