//! Domain policy for AgingBucket aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::AgingBucket;

/// Domain policy for AgingBucket — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<AgingBucket>` in the `// <<< CUSTOM` zone.
pub type AgingBucketDomainPolicy = PermitAllPolicy<AgingBucket>;

// <<< CUSTOM
// END CUSTOM
