//! Domain policy for DunningRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::DunningRun;

/// Domain policy for DunningRun — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<DunningRun>` in the `// <<< CUSTOM` zone.
pub type DunningRunDomainPolicy = PermitAllPolicy<DunningRun>;

// <<< CUSTOM
// END CUSTOM
