//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod mode_of_payment_domain_policy;
pub mod payment_entry_domain_policy;
pub mod payment_allocation_domain_policy;

pub use mode_of_payment_domain_policy::ModeOfPaymentDomainPolicy;
pub use payment_entry_domain_policy::PaymentEntryDomainPolicy;
pub use payment_allocation_domain_policy::PaymentAllocationDomainPolicy;

// <<< CUSTOM
// END CUSTOM
