//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod aging_bucket_domain_policy;
pub mod aging_snapshot_domain_policy;
pub mod dunning_action_domain_policy;
pub mod dunning_run_domain_policy;
pub mod mode_of_payment_domain_policy;
pub mod payment_allocation_domain_policy;
pub mod payment_entry_domain_policy;

pub use aging_bucket_domain_policy::AgingBucketDomainPolicy;
pub use aging_snapshot_domain_policy::AgingSnapshotDomainPolicy;
pub use dunning_action_domain_policy::DunningActionDomainPolicy;
pub use dunning_run_domain_policy::DunningRunDomainPolicy;
pub use mode_of_payment_domain_policy::ModeOfPaymentDomainPolicy;
pub use payment_allocation_domain_policy::PaymentAllocationDomainPolicy;
pub use payment_entry_domain_policy::PaymentEntryDomainPolicy;

// <<< CUSTOM
// END CUSTOM
