//! Application service for AgingSnapshot entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `aging_snapshot_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAgingSnapshotDto, UpdateAgingSnapshotDto};
use crate::domain::entity::AgingSnapshot;
use crate::infrastructure::persistence::AgingSnapshotRepository;

/// Application service for AgingSnapshot entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `aging_snapshot_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AgingSnapshotServiceCustom {
///     inner: Arc<AgingSnapshotService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AgingSnapshotService = GenericCrudService<
    AgingSnapshot,
    CreateAgingSnapshotDto,
    UpdateAgingSnapshotDto,
    AgingSnapshotRepository,
>;

// <<< CUSTOM
// END CUSTOM
