//! Application service for DunningRun entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `dunning_run_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDunningRunDto, UpdateDunningRunDto};
use crate::domain::entity::DunningRun;
use crate::infrastructure::persistence::DunningRunRepository;

/// Application service for DunningRun entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `dunning_run_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DunningRunServiceCustom {
///     inner: Arc<DunningRunService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DunningRunService = GenericCrudService<
    DunningRun,
    CreateDunningRunDto,
    UpdateDunningRunDto,
    DunningRunRepository,
>;

// <<< CUSTOM
// END CUSTOM
