//! Application service for DunningAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `dunning_action_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDunningActionDto, UpdateDunningActionDto};
use crate::domain::entity::DunningAction;
use crate::infrastructure::persistence::DunningActionRepository;

/// Application service for DunningAction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `dunning_action_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DunningActionServiceCustom {
///     inner: Arc<DunningActionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DunningActionService = GenericCrudService<
    DunningAction,
    CreateDunningActionDto,
    UpdateDunningActionDto,
    DunningActionRepository,
>;

// <<< CUSTOM
// END CUSTOM
