//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod mode_of_payment_service;
pub mod payment_entry_service;
pub mod payment_allocation_service;

// <<< CUSTOM
pub mod payment_events;
pub mod payment_gl;
pub mod payment_write_service;
// END CUSTOM

pub use mode_of_payment_service::ModeOfPaymentService;
pub use payment_entry_service::PaymentEntryService;
pub use payment_allocation_service::PaymentAllocationService;
// <<< CUSTOM
pub use payment_events::{
    LoggingSink, PaymentCancelled, PaymentEvent, PaymentEventSink, PaymentReceivedOnAccount,
    PaymentSettled, SettledInvoice,
};
pub use payment_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use payment_write_service::{
    NewAllocation, NewPayment, PaymentError, PaymentWriteService, SettleOutcome,
};
// END CUSTOM