//! Application service for ModeOfPayment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `mode_of_payment_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateModeOfPaymentDto, UpdateModeOfPaymentDto};
use crate::domain::entity::ModeOfPayment;
use crate::infrastructure::persistence::ModeOfPaymentRepository;

/// Application service for ModeOfPayment entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `mode_of_payment_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ModeOfPaymentServiceCustom {
///     inner: Arc<ModeOfPaymentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ModeOfPaymentService = GenericCrudService<
    ModeOfPayment,
    CreateModeOfPaymentDto,
    UpdateModeOfPaymentDto,
    ModeOfPaymentRepository,
>;

// <<< CUSTOM
// END CUSTOM
