//! Application service for PaymentEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `payment_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePaymentEntryDto, UpdatePaymentEntryDto};
use crate::domain::entity::PaymentEntry;
use crate::infrastructure::persistence::PaymentEntryRepository;

/// Application service for PaymentEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `payment_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PaymentEntryServiceCustom {
///     inner: Arc<PaymentEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PaymentEntryService = GenericCrudService<
    PaymentEntry,
    CreatePaymentEntryDto,
    UpdatePaymentEntryDto,
    PaymentEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
