//! Application service for PaymentAllocation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `payment_allocation_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePaymentAllocationDto, UpdatePaymentAllocationDto};
use crate::domain::entity::PaymentAllocation;
use crate::infrastructure::persistence::PaymentAllocationRepository;

/// Application service for PaymentAllocation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `payment_allocation_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PaymentAllocationServiceCustom {
///     inner: Arc<PaymentAllocationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PaymentAllocationService = GenericCrudService<
    PaymentAllocation,
    CreatePaymentAllocationDto,
    UpdatePaymentAllocationDto,
    PaymentAllocationRepository,
>;

// <<< CUSTOM
// END CUSTOM
