-- AgingSnapshot Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.aging_snapshots table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.aging_snapshots (
--     id,
--     company_id,
--     as_of_date,
--     direction,
--     total_outstanding,
--     bucket_current,
--     bucket_1_30,
--     bucket_31_60,
--     bucket_61_90,
--     bucket_90p,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.aging_snapshots (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

