-- AgingBucket Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.aging_buckets table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.aging_buckets (
--     id,
--     company_id,
--     snapshot_id,
--     invoice_ref,
--     invoice_kind,
--     party_id,
--     due_date,
--     days_past_due,
--     outstanding_amount,
--     bucket,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.aging_buckets (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

