-- DunningAction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.dunning_actions table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.dunning_actions (
--     id,
--     company_id,
--     run_id,
--     invoice_ref,
--     invoice_kind,
--     party_id,
--     level,
--     action_type,
--     days_past_due,
--     outstanding_amount,
--     status,
--     processed_at,
--     result_ref,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.dunning_actions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

