-- DunningRun Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.dunning_runs table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.dunning_runs (
--     id,
--     company_id,
--     as_of_date,
--     direction,
--     snapshot_id,
--     actions_emitted,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.dunning_runs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

