-- PaymentAllocation Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.payment_allocations table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.payment_allocations (
--     id,
--     payment_id,
--     invoice_ref,
--     invoice_kind,
--     allocated_amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.payment_allocations (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

