-- PaymentEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payment.payment_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO payment.payment_entries (
--     id,
--     payment_number,
--     company_id,
--     branch_id,
--     payment_type,
--     party_type,
--     party_id,
--     posting_date,
--     currency,
--     mode_of_payment_id,
--     paid_amount,
--     allocated_amount,
--     unallocated_amount,
--     bank_account_id,
--     party_account_id,
--     status,
--     posting_state,
--     journal_id,
--     accounting_post_id,
--     posted_at,
--     reference_no,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payment.payment_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

