-- Company RLS fence for payment module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.
--
-- Ordering note: this migration originally also fenced aging_snapshots,
-- aging_buckets, dunning_runs, and dunning_actions — tables created later in
-- the chain (20260725000002..5) — which made a fresh database fail here with
-- "relation ... does not exist". Those stanzas were added after the tables
-- landed, into this earlier file, invisible to databases that had already
-- applied it (the migration runner records module+name, no checksums). They
-- are removed again; the fence re-statement migration at the end of the chain
-- covers every payment table, so fresh databases still end fully fenced.

-- Migration: company row-level-security fence for payment.payment_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.payment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.payment_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_entries_company_isolation ON payment.payment_entries;
CREATE POLICY payment_entries_company_isolation ON payment.payment_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.payment_allocations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.payment_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.payment_allocations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_allocations_company_isolation ON payment.payment_allocations;
CREATE POLICY payment_allocations_company_isolation ON payment.payment_allocations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
