-- Migration: Create dunning_actions table
-- Generated by metaphor-schema

-- Create dunning_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_level') THEN
        CREATE TYPE dunning_level AS ENUM ('current', 'reminder', 'overdue', 'final_notice', 'collection', 'written_off');
    END IF;
END
$$;

-- Create dunning_action_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_action_type') THEN
        CREATE TYPE dunning_action_type AS ENUM ('send_reminder', 'send_overdue', 'send_final_notice', 'escalate_to_agency', 'recommend_write_off');
    END IF;
END
$$;

-- Create dunning_action_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_action_status') THEN
        CREATE TYPE dunning_action_status AS ENUM ('pending', 'sent', 'failed', 'suppressed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.dunning_actions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    run_id UUID NOT NULL,
    invoice_ref UUID NOT NULL,
    invoice_kind TEXT NOT NULL,
    party_id UUID,
    level dunning_level NOT NULL,
    action_type dunning_action_type NOT NULL,
    days_past_due INTEGER NOT NULL,
    outstanding_amount NUMERIC(18, 2) NOT NULL CHECK (outstanding_amount >= 0),
    status dunning_action_status NOT NULL DEFAULT 'pending',
    processed_at TIMESTAMPTZ,
    result_ref TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_dunning_actions_run_id ON payment.dunning_actions (run_id);

CREATE INDEX IF NOT EXISTS idx_dunning_actions_company_id_party_id_status ON payment.dunning_actions (company_id, party_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dunning_actions_invoice_ref_invoice_kind_level ON payment.dunning_actions (invoice_ref, invoice_kind, level) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_dunning_actions_metadata_gin ON payment.dunning_actions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_dunning_actions_metadata_deleted_at ON payment.dunning_actions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_dunning_actions_metadata_created_at ON payment.dunning_actions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_dunning_actions_metadata_updated_at ON payment.dunning_actions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.dunning_actions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS dunning_actions_insert_audit ON payment.dunning_actions;
CREATE TRIGGER dunning_actions_insert_audit BEFORE INSERT ON payment.dunning_actions
    FOR EACH ROW EXECUTE FUNCTION payment.dunning_actions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS dunning_actions_update_audit ON payment.dunning_actions;
CREATE TRIGGER dunning_actions_update_audit BEFORE UPDATE ON payment.dunning_actions
    FOR EACH ROW EXECUTE FUNCTION payment.dunning_actions_audit_timestamp();
