-- Company RLS fence for payment module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for payment.payment_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.payment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.payment_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_entries_company_isolation ON payment.payment_entries;
CREATE POLICY payment_entries_company_isolation ON payment.payment_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

