-- Enum types for payment module
-- Generated by metaphor-schema

-- Create mode_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mode_type') THEN
        CREATE TYPE mode_type AS ENUM ('cash', 'bank_transfer', 'card', 'e_wallet', 'virtual_account', 'qris');
    END IF;
END
$$;

-- Create payment_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_type') THEN
        CREATE TYPE payment_type AS ENUM ('receive', 'pay', 'internal_transfer');
    END IF;
END
$$;

-- Create payment_party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_party_type') THEN
        CREATE TYPE payment_party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create payment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('draft', 'submitted', 'posted', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

-- Create settlement_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_kind') THEN
        CREATE TYPE settlement_kind AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

