-- Migration: Create payment_entries table
-- Generated by metaphor-schema

-- Create payment_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_type') THEN
        CREATE TYPE payment_type AS ENUM ('receive', 'pay', 'internal_transfer');
    END IF;
END
$$;

-- Create payment_party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_party_type') THEN
        CREATE TYPE payment_party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create payment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('draft', 'submitted', 'posted', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.payment_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    payment_number TEXT NOT NULL,
    company_id UUID NOT NULL,
    branch_id UUID,
    payment_type payment_type NOT NULL,
    party_type payment_party_type,
    party_id UUID,
    posting_date DATE NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    mode_of_payment_id UUID,
    paid_amount NUMERIC(18, 2) NOT NULL CHECK (paid_amount >= 0),
    allocated_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (allocated_amount >= 0),
    unallocated_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (unallocated_amount >= 0),
    bank_account_id UUID NOT NULL,
    party_account_id UUID NOT NULL,
    status payment_status NOT NULL DEFAULT 'draft',
    posting_state gl_posting_state NOT NULL DEFAULT 'pending',
    journal_id UUID,
    accounting_post_id UUID,
    posted_at TIMESTAMPTZ,
    reference_no TEXT,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_entries_payment_number ON payment.payment_entries (payment_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_payment_entries_company_id_party_type_party_id_status ON payment.payment_entries (company_id, party_type, party_id, status);

CREATE INDEX IF NOT EXISTS idx_payment_entries_posting_state ON payment.payment_entries (posting_state);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payment_entries_metadata_gin ON payment.payment_entries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payment_entries_metadata_deleted_at ON payment.payment_entries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payment_entries_metadata_created_at ON payment.payment_entries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payment_entries_metadata_updated_at ON payment.payment_entries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.payment_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_entries_insert_audit ON payment.payment_entries;
CREATE TRIGGER payment_entries_insert_audit BEFORE INSERT ON payment.payment_entries
    FOR EACH ROW EXECUTE FUNCTION payment.payment_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_entries_update_audit ON payment.payment_entries;
CREATE TRIGGER payment_entries_update_audit BEFORE UPDATE ON payment.payment_entries
    FOR EACH ROW EXECUTE FUNCTION payment.payment_entries_audit_timestamp();
