-- Enum types for payment module
-- Generated by metaphor-schema

-- Create aging_bucket_name enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'aging_bucket_name') THEN
        CREATE TYPE aging_bucket_name AS ENUM ('current', 'bucket_1_30', 'bucket_31_60', 'bucket_61_90', 'bucket_90p');
    END IF;
END
$$;

-- Create dunning_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_level') THEN
        CREATE TYPE dunning_level AS ENUM ('current', 'reminder', 'overdue', 'final_notice', 'collection', 'written_off');
    END IF;
END
$$;

-- Create dunning_action_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_action_type') THEN
        CREATE TYPE dunning_action_type AS ENUM ('send_reminder', 'send_overdue', 'send_final_notice', 'escalate_to_agency', 'recommend_write_off');
    END IF;
END
$$;

-- Create dunning_action_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_action_status') THEN
        CREATE TYPE dunning_action_status AS ENUM ('pending', 'sent', 'failed', 'suppressed');
    END IF;
END
$$;

-- Create snapshot_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'snapshot_status') THEN
        CREATE TYPE snapshot_status AS ENUM ('building', 'final', 'aborted');
    END IF;
END
$$;

-- Create dunning_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_run_status') THEN
        CREATE TYPE dunning_run_status AS ENUM ('building', 'completed', 'aborted');
    END IF;
END
$$;

-- Create mode_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mode_type') THEN
        CREATE TYPE mode_type AS ENUM ('cash', 'bank_transfer', 'card', 'e_wallet', 'virtual_account', 'qris');
    END IF;
END
$$;

-- Create payment_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_type') THEN
        CREATE TYPE payment_type AS ENUM ('receive', 'pay', 'internal_transfer');
    END IF;
END
$$;

-- Create payment_party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_party_type') THEN
        CREATE TYPE payment_party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create payment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
        CREATE TYPE payment_status AS ENUM ('draft', 'submitted', 'posted', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

-- `gl_posting_state` is a SHARED enum: several modules post to the GL and each
-- creates this type. Modules never depend on one another, so none of them can
-- own it — whichever migration reaches the database first creates it, and every
-- other one finds it present and does nothing. That is the whole defect: a
-- module that needs a value the first creator did not declare silently gets a
-- narrower type, and fails later when a column default names the missing value.
--
-- So the guard above creates the type when absent, and the statements below
-- guarantee the values THIS module depends on, whoever created it. The result
-- is order-independent: the type ends up as the union of what every module
-- needs, regardless of which one ran first.
--
-- These stay top-level statements on purpose. A new enum value cannot be USED
-- in the transaction that added it, so widening must never share a transaction
-- with a column default that names the new value. This file creates types and
-- nothing else, which is what makes the widening safe here.
ALTER TYPE gl_posting_state ADD VALUE IF NOT EXISTS 'pending';
ALTER TYPE gl_posting_state ADD VALUE IF NOT EXISTS 'posted';
ALTER TYPE gl_posting_state ADD VALUE IF NOT EXISTS 'failed';

-- Create settlement_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_kind') THEN
        CREATE TYPE settlement_kind AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

-- Create withholding_tax_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'withholding_tax_type') THEN
        CREATE TYPE withholding_tax_type AS ENUM ('none', 'pph_22', 'pph_23', 'pph_26');
    END IF;
END
$$;

