-- Audit Triggers Migration for payment module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ModeOfPayment (payment.mode_of_payments)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payment.mode_of_payments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mode_of_payments_insert_audit ON payment.mode_of_payments;
CREATE TRIGGER mode_of_payments_insert_audit BEFORE INSERT ON payment.mode_of_payments
    FOR EACH ROW EXECUTE FUNCTION payment.mode_of_payments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mode_of_payments_update_audit ON payment.mode_of_payments;
CREATE TRIGGER mode_of_payments_update_audit BEFORE UPDATE ON payment.mode_of_payments
    FOR EACH ROW EXECUTE FUNCTION payment.mode_of_payments_audit_timestamp();

-- ==============================================================================
-- Table: PaymentEntry (payment.payment_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payment.payment_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_entries_insert_audit ON payment.payment_entries;
CREATE TRIGGER payment_entries_insert_audit BEFORE INSERT ON payment.payment_entries
    FOR EACH ROW EXECUTE FUNCTION payment.payment_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_entries_update_audit ON payment.payment_entries;
CREATE TRIGGER payment_entries_update_audit BEFORE UPDATE ON payment.payment_entries
    FOR EACH ROW EXECUTE FUNCTION payment.payment_entries_audit_timestamp();

-- ==============================================================================
-- Table: PaymentAllocation (payment.payment_allocations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payment.payment_allocations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_allocations_insert_audit ON payment.payment_allocations;
CREATE TRIGGER payment_allocations_insert_audit BEFORE INSERT ON payment.payment_allocations
    FOR EACH ROW EXECUTE FUNCTION payment.payment_allocations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_allocations_update_audit ON payment.payment_allocations;
CREATE TRIGGER payment_allocations_update_audit BEFORE UPDATE ON payment.payment_allocations
    FOR EACH ROW EXECUTE FUNCTION payment.payment_allocations_audit_timestamp();

