-- Migration: Create aging_snapshots table
-- Generated by metaphor-schema

-- Create snapshot_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'snapshot_status') THEN
        CREATE TYPE snapshot_status AS ENUM ('building', 'final', 'aborted');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.aging_snapshots (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    as_of_date DATE NOT NULL,
    direction TEXT NOT NULL,
    total_outstanding NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total_outstanding >= 0),
    bucket_current NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (bucket_current >= 0),
    bucket_1_30 NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (bucket_1_30 >= 0),
    bucket_31_60 NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (bucket_31_60 >= 0),
    bucket_61_90 NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (bucket_61_90 >= 0),
    bucket_90p NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (bucket_90p >= 0),
    status snapshot_status NOT NULL DEFAULT 'building',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_aging_snapshots_company_id_as_of_date_direction ON payment.aging_snapshots (company_id, as_of_date, direction) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_aging_snapshots_company_id_as_of_date ON payment.aging_snapshots (company_id, as_of_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_aging_snapshots_metadata_gin ON payment.aging_snapshots USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_aging_snapshots_metadata_deleted_at ON payment.aging_snapshots ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_aging_snapshots_metadata_created_at ON payment.aging_snapshots ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_aging_snapshots_metadata_updated_at ON payment.aging_snapshots ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.aging_snapshots_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS aging_snapshots_insert_audit ON payment.aging_snapshots;
CREATE TRIGGER aging_snapshots_insert_audit BEFORE INSERT ON payment.aging_snapshots
    FOR EACH ROW EXECUTE FUNCTION payment.aging_snapshots_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS aging_snapshots_update_audit ON payment.aging_snapshots;
CREATE TRIGGER aging_snapshots_update_audit BEFORE UPDATE ON payment.aging_snapshots
    FOR EACH ROW EXECUTE FUNCTION payment.aging_snapshots_audit_timestamp();
