-- Company RLS fence for payment module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for payment.aging_snapshots
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.aging_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.aging_snapshots FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS aging_snapshots_company_isolation ON payment.aging_snapshots;
CREATE POLICY aging_snapshots_company_isolation ON payment.aging_snapshots
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.aging_buckets
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.aging_buckets ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.aging_buckets FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS aging_buckets_company_isolation ON payment.aging_buckets;
CREATE POLICY aging_buckets_company_isolation ON payment.aging_buckets
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.dunning_runs
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.dunning_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.dunning_runs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dunning_runs_company_isolation ON payment.dunning_runs;
CREATE POLICY dunning_runs_company_isolation ON payment.dunning_runs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.dunning_actions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.dunning_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.dunning_actions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dunning_actions_company_isolation ON payment.dunning_actions;
CREATE POLICY dunning_actions_company_isolation ON payment.dunning_actions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.payment_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.payment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.payment_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_entries_company_isolation ON payment.payment_entries;
CREATE POLICY payment_entries_company_isolation ON payment.payment_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payment.payment_allocations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payment.payment_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment.payment_allocations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payment_allocations_company_isolation ON payment.payment_allocations;
CREATE POLICY payment_allocations_company_isolation ON payment.payment_allocations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

