-- Migration: Create payment_allocations table
-- Generated by metaphor-schema

-- Create settlement_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_kind') THEN
        CREATE TYPE settlement_kind AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.payment_allocations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    payment_id UUID NOT NULL,
    invoice_ref UUID NOT NULL,
    invoice_kind settlement_kind NOT NULL,
    allocated_amount NUMERIC(18, 2) NOT NULL CHECK (allocated_amount >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_payment_allocations_payment_id ON payment.payment_allocations (payment_id);

CREATE INDEX IF NOT EXISTS idx_payment_allocations_invoice_ref_invoice_kind ON payment.payment_allocations (invoice_ref, invoice_kind);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payment_allocations_metadata_gin ON payment.payment_allocations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payment_allocations_metadata_deleted_at ON payment.payment_allocations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payment_allocations_metadata_created_at ON payment.payment_allocations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payment_allocations_metadata_updated_at ON payment.payment_allocations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.payment_allocations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_allocations_insert_audit ON payment.payment_allocations;
CREATE TRIGGER payment_allocations_insert_audit BEFORE INSERT ON payment.payment_allocations
    FOR EACH ROW EXECUTE FUNCTION payment.payment_allocations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_allocations_update_audit ON payment.payment_allocations;
CREATE TRIGGER payment_allocations_update_audit BEFORE UPDATE ON payment.payment_allocations
    FOR EACH ROW EXECUTE FUNCTION payment.payment_allocations_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE payment.payment_allocations ADD CONSTRAINT fk_payment_allocations_payment_id FOREIGN KEY (payment_id) REFERENCES payment.payment_entries (id);
