-- Migration: Create mode_of_payments table
-- Generated by metaphor-schema

-- Create mode_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'mode_type') THEN
        CREATE TYPE mode_type AS ENUM ('cash', 'bank_transfer', 'card', 'e_wallet', 'virtual_account', 'qris');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.mode_of_payments (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    mode_type mode_type NOT NULL,
    default_account_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mode_of_payments_code ON payment.mode_of_payments (code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_mode_of_payments_mode_type_is_active ON payment.mode_of_payments (mode_type, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_mode_of_payments_metadata_gin ON payment.mode_of_payments USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_mode_of_payments_metadata_deleted_at ON payment.mode_of_payments ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_mode_of_payments_metadata_created_at ON payment.mode_of_payments ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_mode_of_payments_metadata_updated_at ON payment.mode_of_payments ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.mode_of_payments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS mode_of_payments_insert_audit ON payment.mode_of_payments;
CREATE TRIGGER mode_of_payments_insert_audit BEFORE INSERT ON payment.mode_of_payments
    FOR EACH ROW EXECUTE FUNCTION payment.mode_of_payments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS mode_of_payments_update_audit ON payment.mode_of_payments;
CREATE TRIGGER mode_of_payments_update_audit BEFORE UPDATE ON payment.mode_of_payments
    FOR EACH ROW EXECUTE FUNCTION payment.mode_of_payments_audit_timestamp();
