-- Migration: Create dunning_runs table
-- Generated by metaphor-schema

-- Create dunning_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dunning_run_status') THEN
        CREATE TYPE dunning_run_status AS ENUM ('building', 'completed', 'aborted');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TABLE IF NOT EXISTS payment.dunning_runs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    as_of_date DATE NOT NULL,
    direction TEXT NOT NULL,
    snapshot_id UUID,
    actions_emitted INTEGER NOT NULL DEFAULT 0,
    status dunning_run_status NOT NULL DEFAULT 'building',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_dunning_runs_company_id_as_of_date ON payment.dunning_runs (company_id, as_of_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_dunning_runs_metadata_gin ON payment.dunning_runs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_dunning_runs_metadata_deleted_at ON payment.dunning_runs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_dunning_runs_metadata_created_at ON payment.dunning_runs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_dunning_runs_metadata_updated_at ON payment.dunning_runs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payment.dunning_runs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS dunning_runs_insert_audit ON payment.dunning_runs;
CREATE TRIGGER dunning_runs_insert_audit BEFORE INSERT ON payment.dunning_runs
    FOR EACH ROW EXECUTE FUNCTION payment.dunning_runs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS dunning_runs_update_audit ON payment.dunning_runs;
CREATE TRIGGER dunning_runs_update_audit BEFORE UPDATE ON payment.dunning_runs
    FOR EACH ROW EXECUTE FUNCTION payment.dunning_runs_audit_timestamp();
