//! Event handler trait for AgingBucket events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::AgingBucketEvent;
use backbone_messaging::EventHandler;

/// Event handler for AgingBucket events.
/// Implement this trait to react to AgingBucket lifecycle events.
pub trait AgingBucketEventHandler: EventHandler<AgingBucketEvent> {}
