//! Event handler trait for AgingSnapshot events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::AgingSnapshotEvent;
use backbone_messaging::EventHandler;

/// Event handler for AgingSnapshot events.
/// Implement this trait to react to AgingSnapshot lifecycle events.
pub trait AgingSnapshotEventHandler: EventHandler<AgingSnapshotEvent> {}
