//! Event handler trait for AgingSnapshot events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AgingSnapshotEvent;

/// Event handler for AgingSnapshot events.
/// Implement this trait to react to AgingSnapshot lifecycle events.
pub trait AgingSnapshotEventHandler: EventHandler<AgingSnapshotEvent> {}
