//! Domain events for AgingSnapshot entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AgingSnapshot;

/// Domain events for AgingSnapshot — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AgingSnapshot>)` variant.
pub type AgingSnapshotEvent = CrudEvent<AgingSnapshot>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AgingSnapshot events.
pub type AgingSnapshotEventPublisher = Arc<dyn CrudEventPublisher<AgingSnapshot> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAgingSnapshotEventPublisher = NoOpCrudEventPublisher<AgingSnapshot>;
