//! Event handler trait for DunningAction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::DunningActionEvent;
use backbone_messaging::EventHandler;

/// Event handler for DunningAction events.
/// Implement this trait to react to DunningAction lifecycle events.
pub trait DunningActionEventHandler: EventHandler<DunningActionEvent> {}
