//! Event handler trait for DunningRun events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::DunningRunEvent;
use backbone_messaging::EventHandler;

/// Event handler for DunningRun events.
/// Implement this trait to react to DunningRun lifecycle events.
pub trait DunningRunEventHandler: EventHandler<DunningRunEvent> {}
