//! Domain events for DunningAction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DunningAction;

/// Domain events for DunningAction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DunningAction>)` variant.
pub type DunningActionEvent = CrudEvent<DunningAction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DunningAction events.
pub type DunningActionEventPublisher = Arc<dyn CrudEventPublisher<DunningAction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDunningActionEventPublisher = NoOpCrudEventPublisher<DunningAction>;
