//! Domain events for DunningRun entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DunningRun;

/// Domain events for DunningRun — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DunningRun>)` variant.
pub type DunningRunEvent = CrudEvent<DunningRun>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DunningRun events.
pub type DunningRunEventPublisher = Arc<dyn CrudEventPublisher<DunningRun> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDunningRunEventPublisher = NoOpCrudEventPublisher<DunningRun>;
