//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod aging_snapshot_events;
pub mod aging_snapshot_event_handlers;
pub mod aging_bucket_events;
pub mod aging_bucket_event_handlers;
pub mod dunning_run_events;
pub mod dunning_run_event_handlers;
pub mod dunning_action_events;
pub mod dunning_action_event_handlers;
pub mod mode_of_payment_events;
pub mod mode_of_payment_event_handlers;
pub mod payment_entry_events;
pub mod payment_entry_event_handlers;
pub mod payment_allocation_events;
pub mod payment_allocation_event_handlers;

pub use aging_snapshot_events::{AgingSnapshotEvent, AgingSnapshotEventPublisher, NoopAgingSnapshotEventPublisher};
pub use aging_snapshot_event_handlers::AgingSnapshotEventHandler;
pub use aging_bucket_events::{AgingBucketEvent, AgingBucketEventPublisher, NoopAgingBucketEventPublisher};
pub use aging_bucket_event_handlers::AgingBucketEventHandler;
pub use dunning_run_events::{DunningRunEvent, DunningRunEventPublisher, NoopDunningRunEventPublisher};
pub use dunning_run_event_handlers::DunningRunEventHandler;
pub use dunning_action_events::{DunningActionEvent, DunningActionEventPublisher, NoopDunningActionEventPublisher};
pub use dunning_action_event_handlers::DunningActionEventHandler;
pub use mode_of_payment_events::{ModeOfPaymentEvent, ModeOfPaymentEventPublisher, NoopModeOfPaymentEventPublisher};
pub use mode_of_payment_event_handlers::ModeOfPaymentEventHandler;
pub use payment_entry_events::{PaymentEntryEvent, PaymentEntryEventPublisher, NoopPaymentEntryEventPublisher};
pub use payment_entry_event_handlers::PaymentEntryEventHandler;
pub use payment_allocation_events::{PaymentAllocationEvent, PaymentAllocationEventPublisher, NoopPaymentAllocationEventPublisher};
pub use payment_allocation_event_handlers::PaymentAllocationEventHandler;

// <<< CUSTOM
// END CUSTOM
