//! Event handler trait for ModeOfPayment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ModeOfPaymentEvent;

/// Event handler for ModeOfPayment events.
/// Implement this trait to react to ModeOfPayment lifecycle events.
pub trait ModeOfPaymentEventHandler: EventHandler<ModeOfPaymentEvent> {}
