//! Event handler trait for PaymentAllocation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PaymentAllocationEvent;

/// Event handler for PaymentAllocation events.
/// Implement this trait to react to PaymentAllocation lifecycle events.
pub trait PaymentAllocationEventHandler: EventHandler<PaymentAllocationEvent> {}
