//! Domain events for PaymentEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PaymentEntry;

/// Domain events for PaymentEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentEntry>)` variant.
pub type PaymentEntryEvent = CrudEvent<PaymentEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentEntry events.
pub type PaymentEntryEventPublisher = Arc<dyn CrudEventPublisher<PaymentEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentEntryEventPublisher = NoOpCrudEventPublisher<PaymentEntry>;
