//! Event handler trait for PaymentEntry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PaymentEntryEvent;

/// Event handler for PaymentEntry events.
/// Implement this trait to react to PaymentEntry lifecycle events.
pub trait PaymentEntryEventHandler: EventHandler<PaymentEntryEvent> {}
