//! Domain events for PaymentAllocation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PaymentAllocation;

/// Domain events for PaymentAllocation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentAllocation>)` variant.
pub type PaymentAllocationEvent = CrudEvent<PaymentAllocation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentAllocation events.
pub type PaymentAllocationEventPublisher = Arc<dyn CrudEventPublisher<PaymentAllocation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentAllocationEventPublisher = NoOpCrudEventPublisher<PaymentAllocation>;
