//! Event subscriber type aliases for Payment module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::ModeOfPaymentEvent;
use crate::domain::event::PaymentEntryEvent;
use crate::domain::event::PaymentAllocationEvent;

/// Subscriber for ModeOfPayment events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ModeOfPaymentEventSubscriber = GenericEventSubscriber<ModeOfPaymentEvent>;

/// Subscriber for PaymentEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentEntryEventSubscriber = GenericEventSubscriber<PaymentEntryEvent>;

/// Subscriber for PaymentAllocation events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentAllocationEventSubscriber = GenericEventSubscriber<PaymentAllocationEvent>;

// <<< CUSTOM
// END CUSTOM
