//! AgingSnapshot seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AgingSnapshot data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// AGINGSNAPSHOT SEEDER
// ============================================================================

/// Seeder for aging_snapshot
pub struct SeedAgingSnapshotSeeder;

impl SeedAgingSnapshotSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAgingSnapshotSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAgingSnapshotSeeder {
    fn name(&self) -> &'static str {
        "SeedAgingSnapshotSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payment.aging_snapshots table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payment.aging_snapshots")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/aging_snapshot_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payment.aging_snapshots")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

