//! AgingBucket seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AgingBucket data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// AGINGBUCKET SEEDER
// ============================================================================

/// Seeder for aging_bucket
pub struct SeedAgingBucketSeeder;

impl SeedAgingBucketSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAgingBucketSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAgingBucketSeeder {
    fn name(&self) -> &'static str {
        "SeedAgingBucketSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payment.aging_buckets table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payment.aging_buckets")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/aging_bucket_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payment.aging_buckets")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

