//! Repository trait for AgingSnapshot aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AgingSnapshot aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AgingSnapshot, SnapshotStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AgingSnapshotPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AgingSnapshotPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AgingSnapshotPaginatedResult {
    pub data: Vec<AgingSnapshot>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AgingSnapshotFilter {
    pub company_id: Option<Uuid>,
    pub direction: Option<String>,
    pub status: Option<SnapshotStatus>,
}

impl AgingSnapshotFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.direction.is_some() || self.status.is_some()
    }
}

/// Repository trait for AgingSnapshot aggregate
///
/// This trait defines the persistence contract for AgingSnapshot entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AgingSnapshotRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new aging_snapshot entity
    async fn save(&self, entity: &AgingSnapshot) -> Result<AgingSnapshot>;

    /// Find aging_snapshot by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AgingSnapshot>>;

    /// Find all aging_snapshot entities
    async fn find_all(&self) -> Result<Vec<AgingSnapshot>>;

    /// Update aging_snapshot by ID
    async fn update(&self, id: &str, entity: &AgingSnapshot) -> Result<Option<AgingSnapshot>>;

    /// Delete aging_snapshot by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List aging_snapshot with pagination
    async fn list(&self, params: AgingSnapshotPaginationParams) -> Result<AgingSnapshotPaginatedResult>;

    /// List aging_snapshot with pagination and filters
    async fn list_with_filters(&self, params: AgingSnapshotPaginationParams, filters: AgingSnapshotFilter) -> Result<AgingSnapshotPaginatedResult>;

    /// Count all aging_snapshot entities
    async fn count(&self) -> Result<u64>;

    /// Count aging_snapshot entities matching filters
    async fn count_with_filters(&self, filters: AgingSnapshotFilter) -> Result<u64>;

    /// Check if aging_snapshot exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete aging_snapshot by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted aging_snapshot by ID
    async fn restore(&self, id: &str) -> Result<Option<AgingSnapshot>>;

    /// List soft-deleted aging_snapshot entities
    async fn list_deleted(&self, params: AgingSnapshotPaginationParams) -> Result<AgingSnapshotPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save aging_snapshot entities
    async fn bulk_save(&self, entities: &[AgingSnapshot]) -> Result<Vec<AgingSnapshot>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
