//! Repository trait for AgingBucket aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AgingBucket aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AgingBucket, AgingBucketName};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AgingBucketPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AgingBucketPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AgingBucketPaginatedResult {
    pub data: Vec<AgingBucket>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AgingBucketFilter {
    pub company_id: Option<Uuid>,
    pub snapshot_id: Option<Uuid>,
    pub invoice_ref: Option<Uuid>,
    pub invoice_kind: Option<String>,
    pub party_id: Option<Uuid>,
    pub bucket: Option<AgingBucketName>,
}

impl AgingBucketFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.snapshot_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.party_id.is_some() || self.bucket.is_some()
    }
}

/// Repository trait for AgingBucket aggregate
///
/// This trait defines the persistence contract for AgingBucket entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AgingBucketRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new aging_bucket entity
    async fn save(&self, entity: &AgingBucket) -> Result<AgingBucket>;

    /// Find aging_bucket by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AgingBucket>>;

    /// Find all aging_bucket entities
    async fn find_all(&self) -> Result<Vec<AgingBucket>>;

    /// Update aging_bucket by ID
    async fn update(&self, id: &str, entity: &AgingBucket) -> Result<Option<AgingBucket>>;

    /// Delete aging_bucket by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List aging_bucket with pagination
    async fn list(&self, params: AgingBucketPaginationParams) -> Result<AgingBucketPaginatedResult>;

    /// List aging_bucket with pagination and filters
    async fn list_with_filters(&self, params: AgingBucketPaginationParams, filters: AgingBucketFilter) -> Result<AgingBucketPaginatedResult>;

    /// Count all aging_bucket entities
    async fn count(&self) -> Result<u64>;

    /// Count aging_bucket entities matching filters
    async fn count_with_filters(&self, filters: AgingBucketFilter) -> Result<u64>;

    /// Check if aging_bucket exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete aging_bucket by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted aging_bucket by ID
    async fn restore(&self, id: &str) -> Result<Option<AgingBucket>>;

    /// List soft-deleted aging_bucket entities
    async fn list_deleted(&self, params: AgingBucketPaginationParams) -> Result<AgingBucketPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save aging_bucket entities
    async fn bulk_save(&self, entities: &[AgingBucket]) -> Result<Vec<AgingBucket>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
