//! Repository trait for DunningAction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DunningAction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DunningAction, DunningActionStatus, DunningActionType, DunningLevel};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DunningActionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DunningActionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DunningActionPaginatedResult {
    pub data: Vec<DunningAction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DunningActionFilter {
    pub company_id: Option<Uuid>,
    pub run_id: Option<Uuid>,
    pub invoice_ref: Option<Uuid>,
    pub invoice_kind: Option<String>,
    pub party_id: Option<Uuid>,
    pub level: Option<DunningLevel>,
    pub action_type: Option<DunningActionType>,
    pub status: Option<DunningActionStatus>,
    pub result_ref: Option<String>,
}

impl DunningActionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.run_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.party_id.is_some() || self.level.is_some() || self.action_type.is_some() || self.status.is_some() || self.result_ref.is_some()
    }
}

/// Repository trait for DunningAction aggregate
///
/// This trait defines the persistence contract for DunningAction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DunningActionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new dunning_action entity
    async fn save(&self, entity: &DunningAction) -> Result<DunningAction>;

    /// Find dunning_action by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DunningAction>>;

    /// Find all dunning_action entities
    async fn find_all(&self) -> Result<Vec<DunningAction>>;

    /// Update dunning_action by ID
    async fn update(&self, id: &str, entity: &DunningAction) -> Result<Option<DunningAction>>;

    /// Delete dunning_action by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List dunning_action with pagination
    async fn list(&self, params: DunningActionPaginationParams) -> Result<DunningActionPaginatedResult>;

    /// List dunning_action with pagination and filters
    async fn list_with_filters(&self, params: DunningActionPaginationParams, filters: DunningActionFilter) -> Result<DunningActionPaginatedResult>;

    /// Count all dunning_action entities
    async fn count(&self) -> Result<u64>;

    /// Count dunning_action entities matching filters
    async fn count_with_filters(&self, filters: DunningActionFilter) -> Result<u64>;

    /// Check if dunning_action exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete dunning_action by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted dunning_action by ID
    async fn restore(&self, id: &str) -> Result<Option<DunningAction>>;

    /// List soft-deleted dunning_action entities
    async fn list_deleted(&self, params: DunningActionPaginationParams) -> Result<DunningActionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save dunning_action entities
    async fn bulk_save(&self, entities: &[DunningAction]) -> Result<Vec<DunningAction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
