//! Repository trait for DunningRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DunningRun aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DunningRun, DunningRunStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DunningRunPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DunningRunPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DunningRunPaginatedResult {
    pub data: Vec<DunningRun>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DunningRunFilter {
    pub company_id: Option<Uuid>,
    pub direction: Option<String>,
    pub snapshot_id: Option<Uuid>,
    pub status: Option<DunningRunStatus>,
}

impl DunningRunFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.direction.is_some() || self.snapshot_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for DunningRun aggregate
///
/// This trait defines the persistence contract for DunningRun entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DunningRunRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new dunning_run entity
    async fn save(&self, entity: &DunningRun) -> Result<DunningRun>;

    /// Find dunning_run by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DunningRun>>;

    /// Find all dunning_run entities
    async fn find_all(&self) -> Result<Vec<DunningRun>>;

    /// Update dunning_run by ID
    async fn update(&self, id: &str, entity: &DunningRun) -> Result<Option<DunningRun>>;

    /// Delete dunning_run by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List dunning_run with pagination
    async fn list(&self, params: DunningRunPaginationParams) -> Result<DunningRunPaginatedResult>;

    /// List dunning_run with pagination and filters
    async fn list_with_filters(&self, params: DunningRunPaginationParams, filters: DunningRunFilter) -> Result<DunningRunPaginatedResult>;

    /// Count all dunning_run entities
    async fn count(&self) -> Result<u64>;

    /// Count dunning_run entities matching filters
    async fn count_with_filters(&self, filters: DunningRunFilter) -> Result<u64>;

    /// Check if dunning_run exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete dunning_run by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted dunning_run by ID
    async fn restore(&self, id: &str) -> Result<Option<DunningRun>>;

    /// List soft-deleted dunning_run entities
    async fn list_deleted(&self, params: DunningRunPaginationParams) -> Result<DunningRunPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save dunning_run entities
    async fn bulk_save(&self, entities: &[DunningRun]) -> Result<Vec<DunningRun>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
