//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod aging_bucket_repository;
pub mod aging_snapshot_repository;
pub mod dunning_action_repository;
pub mod dunning_run_repository;
pub mod mode_of_payment_repository;
pub mod payment_allocation_repository;
pub mod payment_entry_repository;

// Re-exports
pub use aging_bucket_repository::{
    AgingBucketFilter, AgingBucketPaginatedResult, AgingBucketPaginationParams,
    AgingBucketRepository,
};
pub use aging_snapshot_repository::{
    AgingSnapshotFilter, AgingSnapshotPaginatedResult, AgingSnapshotPaginationParams,
    AgingSnapshotRepository,
};
pub use dunning_action_repository::{
    DunningActionFilter, DunningActionPaginatedResult, DunningActionPaginationParams,
    DunningActionRepository,
};
pub use dunning_run_repository::{
    DunningRunFilter, DunningRunPaginatedResult, DunningRunPaginationParams, DunningRunRepository,
};
pub use mode_of_payment_repository::{
    ModeOfPaymentFilter, ModeOfPaymentPaginatedResult, ModeOfPaymentPaginationParams,
    ModeOfPaymentRepository,
};
pub use payment_allocation_repository::{
    PaymentAllocationFilter, PaymentAllocationPaginatedResult, PaymentAllocationPaginationParams,
    PaymentAllocationRepository,
};
pub use payment_entry_repository::{
    PaymentEntryFilter, PaymentEntryPaginatedResult, PaymentEntryPaginationParams,
    PaymentEntryRepository,
};
