//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod mode_of_payment_repository;
pub mod payment_entry_repository;
pub mod payment_allocation_repository;

// Re-exports
pub use mode_of_payment_repository::{
    ModeOfPaymentRepository,
    ModeOfPaymentPaginationParams,
    ModeOfPaymentPaginatedResult,
    ModeOfPaymentFilter,
};
pub use payment_entry_repository::{
    PaymentEntryRepository,
    PaymentEntryPaginationParams,
    PaymentEntryPaginatedResult,
    PaymentEntryFilter,
};
pub use payment_allocation_repository::{
    PaymentAllocationRepository,
    PaymentAllocationPaginationParams,
    PaymentAllocationPaginatedResult,
    PaymentAllocationFilter,
};
