//! Repository trait for ModeOfPayment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ModeOfPayment aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ModeOfPayment, ModeType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ModeOfPaymentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ModeOfPaymentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ModeOfPaymentPaginatedResult {
    pub data: Vec<ModeOfPayment>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ModeOfPaymentFilter {
    pub code: Option<String>,
    pub name: Option<String>,
    pub mode_type: Option<ModeType>,
    pub default_account_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl ModeOfPaymentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.code.is_some() || self.name.is_some() || self.mode_type.is_some() || self.default_account_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for ModeOfPayment aggregate
///
/// This trait defines the persistence contract for ModeOfPayment entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ModeOfPaymentRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new mode_of_payment entity
    async fn save(&self, entity: &ModeOfPayment) -> Result<ModeOfPayment>;

    /// Find mode_of_payment by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ModeOfPayment>>;

    /// Find all mode_of_payment entities
    async fn find_all(&self) -> Result<Vec<ModeOfPayment>>;

    /// Update mode_of_payment by ID
    async fn update(&self, id: &str, entity: &ModeOfPayment) -> Result<Option<ModeOfPayment>>;

    /// Delete mode_of_payment by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List mode_of_payment with pagination
    async fn list(&self, params: ModeOfPaymentPaginationParams) -> Result<ModeOfPaymentPaginatedResult>;

    /// List mode_of_payment with pagination and filters
    async fn list_with_filters(&self, params: ModeOfPaymentPaginationParams, filters: ModeOfPaymentFilter) -> Result<ModeOfPaymentPaginatedResult>;

    /// Count all mode_of_payment entities
    async fn count(&self) -> Result<u64>;

    /// Count mode_of_payment entities matching filters
    async fn count_with_filters(&self, filters: ModeOfPaymentFilter) -> Result<u64>;

    /// Check if mode_of_payment exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete mode_of_payment by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted mode_of_payment by ID
    async fn restore(&self, id: &str) -> Result<Option<ModeOfPayment>>;

    /// List soft-deleted mode_of_payment entities
    async fn list_deleted(&self, params: ModeOfPaymentPaginationParams) -> Result<ModeOfPaymentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save mode_of_payment entities
    async fn bulk_save(&self, entities: &[ModeOfPayment]) -> Result<Vec<ModeOfPayment>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
