//! Repository trait for PaymentAllocation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PaymentAllocation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PaymentAllocation, SettlementKind};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentAllocationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PaymentAllocationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PaymentAllocationPaginatedResult {
    pub data: Vec<PaymentAllocation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentAllocationFilter {
    pub payment_id: Option<Uuid>,
    pub invoice_ref: Option<Uuid>,
    pub invoice_kind: Option<SettlementKind>,
}

impl PaymentAllocationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.payment_id.is_some() || self.invoice_ref.is_some() || self.invoice_kind.is_some()
    }
}

/// Repository trait for PaymentAllocation aggregate
///
/// This trait defines the persistence contract for PaymentAllocation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PaymentAllocationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new payment_allocation entity
    async fn save(&self, entity: &PaymentAllocation) -> Result<PaymentAllocation>;

    /// Find payment_allocation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PaymentAllocation>>;

    /// Find all payment_allocation entities
    async fn find_all(&self) -> Result<Vec<PaymentAllocation>>;

    /// Update payment_allocation by ID
    async fn update(&self, id: &str, entity: &PaymentAllocation) -> Result<Option<PaymentAllocation>>;

    /// Delete payment_allocation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List payment_allocation with pagination
    async fn list(&self, params: PaymentAllocationPaginationParams) -> Result<PaymentAllocationPaginatedResult>;

    /// List payment_allocation with pagination and filters
    async fn list_with_filters(&self, params: PaymentAllocationPaginationParams, filters: PaymentAllocationFilter) -> Result<PaymentAllocationPaginatedResult>;

    /// Count all payment_allocation entities
    async fn count(&self) -> Result<u64>;

    /// Count payment_allocation entities matching filters
    async fn count_with_filters(&self, filters: PaymentAllocationFilter) -> Result<u64>;

    /// Check if payment_allocation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete payment_allocation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted payment_allocation by ID
    async fn restore(&self, id: &str) -> Result<Option<PaymentAllocation>>;

    /// List soft-deleted payment_allocation entities
    async fn list_deleted(&self, params: PaymentAllocationPaginationParams) -> Result<PaymentAllocationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save payment_allocation entities
    async fn bulk_save(&self, entities: &[PaymentAllocation]) -> Result<Vec<PaymentAllocation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
