//! Repository for AgingSnapshot entities
//!
//! Originally generated by metaphor-schema; now user-owned — declared under user_owned in
//! metaphor.codegen.yaml. The custom methods below hold the dunning SQL (4-layer rule).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AgingSnapshot, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::AgingSnapshot;

/// Table name for AgingSnapshot entities
pub const TABLE_NAME: &str = "payment.aging_snapshots";

/// Repository for AgingSnapshot entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AgingSnapshotRepository(
    backbone_orm::GenericCrudRepository<AgingSnapshot, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AgingSnapshotRepository {
    type Target = backbone_orm::GenericCrudRepository<AgingSnapshot, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AgingSnapshotRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The five aging buckets + the running total the snapshot's `update_totals` writes. Field order
/// matches the column order in the UPDATE; the service computes `total_outstanding` as the sum of
/// the five buckets (the orchestration that owns the bucketing math).
pub struct AgingTotals {
    pub total_outstanding: Decimal,
    pub bucket_current: Decimal,
    pub bucket_1_30: Decimal,
    pub bucket_31_60: Decimal,
    pub bucket_61_90: Decimal,
    pub bucket_90p: Decimal,
}

/// Dunning/aging snapshot SQL. Lives here (not in the service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl AgingSnapshotRepository {
    /// Idempotent snapshot upsert (unique `company + as_of + direction` fence).
    ///
    /// Takes the CALLER'S connection so the snapshot and its buckets commit as one unit. The caller
    /// has already bound the company on it (`bind_company_on`) — don't re-bind here. On conflict the
    /// existing row is reused (status reset to `final`) and its id returned.
    pub async fn upsert_snapshot(
        &self,
        conn: &mut PgConnection,
        id: Uuid,
        company_id: Uuid,
        as_of: NaiveDate,
        direction: &str,
    ) -> Result<Uuid, sqlx::Error> {
        let snapshot_id = sqlx::query_scalar(
            r#"INSERT INTO payment.aging_snapshots (id, company_id, as_of_date, direction, status)
               VALUES ($1, $2, $3, $4, 'final'::snapshot_status)
               ON CONFLICT (company_id, as_of_date, direction) WHERE (metadata->>'deleted_at') IS NULL
               DO UPDATE SET status = 'final'::snapshot_status
               RETURNING id"#,
        )
        .bind(id).bind(company_id).bind(as_of).bind(direction)
        .fetch_one(conn).await?;
        Ok(snapshot_id)
    }

    /// Persist the per-snapshot bucket totals once the per-invoice buckets are written. Same
    /// tx-binding contract as [`Self::upsert_snapshot`].
    pub async fn update_totals(
        &self,
        conn: &mut PgConnection,
        snapshot_id: Uuid,
        totals: &AgingTotals,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE payment.aging_snapshots
                 SET total_outstanding = $2, bucket_current = $3, bucket_1_30 = $4,
                     bucket_31_60 = $5, bucket_61_90 = $6, bucket_90p = $7
               WHERE id = $1"#,
        )
        .bind(snapshot_id).bind(totals.total_outstanding)
        .bind(totals.bucket_current).bind(totals.bucket_1_30).bind(totals.bucket_31_60)
        .bind(totals.bucket_61_90).bind(totals.bucket_90p)
        .execute(conn).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(AgingSnapshotRepository, AgingSnapshot, soft_delete);
