//! Repository for AgingBucket entities
//!
//! Originally generated by metaphor-schema; now user-owned — declared under user_owned in
//! metaphor.codegen.yaml. The custom methods below hold the dunning SQL (4-layer rule).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::AgingBucket;

/// Table name for AgingBucket entities
pub const TABLE_NAME: &str = "payment.aging_buckets";

/// Repository for AgingBucket entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AgingBucketRepository(
    backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AgingBucketRepository {
    type Target = backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AgingBucketRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an aging-bucket insert writes. The service computes `due_date` (with the
/// `as_of` fallback), `days_past_due` (`dpd as i32`), and `bucket` (the `bucket_name(dpd)`
/// mapping) before handing the row to [`AgingBucketRepository::insert_bucket`]; the row mirrors
/// the raw column shape, with `bucket` binding as `&str` and a DB-side cast (`$10::aging_bucket_name`).
pub struct NewAgingBucketRow<'a> {
    pub id: Uuid,
    pub snapshot_id: Uuid,
    pub company_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: &'a str,
    pub party_id: Option<Uuid>,
    pub due_date: NaiveDate,
    pub days_past_due: i32,
    pub outstanding_amount: Decimal,
    pub bucket: &'a str,
}

/// Dunning/aging bucket SQL. Lives here (not in the service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl AgingBucketRepository {
    /// Insert one per-invoice aging-bucket row.
    ///
    /// Takes the CALLER'S connection so each bucket commits with the snapshot it belongs to. The
    /// caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_bucket(
        &self,
        conn: &mut PgConnection,
        b: &NewAgingBucketRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO payment.aging_buckets
                 (id, snapshot_id, company_id, invoice_ref, invoice_kind, party_id,
                  due_date, days_past_due, outstanding_amount, bucket)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::aging_bucket_name)"#,
        )
        .bind(b.id).bind(b.snapshot_id).bind(b.company_id)
        .bind(b.invoice_ref).bind(b.invoice_kind).bind(b.party_id)
        .bind(b.due_date).bind(b.days_past_due).bind(b.outstanding_amount)
        .bind(b.bucket)
        .execute(conn).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(AgingBucketRepository, AgingBucket, soft_delete);
