//! Repository for AgingBucket entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AgingBucket;

/// Table name for AgingBucket entities
pub const TABLE_NAME: &str = "payment.aging_buckets";

/// Repository for AgingBucket entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AgingBucketRepository(
    backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AgingBucketRepository {
    type Target = backbone_orm::GenericCrudRepository<AgingBucket, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AgingBucketRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AgingBucketRepository, AgingBucket, soft_delete);
