//! Repository for DunningAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DunningAction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::DunningAction;

/// Table name for DunningAction entities
pub const TABLE_NAME: &str = "payment.dunning_actions";

/// Repository for DunningAction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DunningActionRepository(
    backbone_orm::GenericCrudRepository<DunningAction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DunningActionRepository {
    type Target = backbone_orm::GenericCrudRepository<DunningAction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DunningActionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(DunningActionRepository, DunningAction, soft_delete);
