//! Repository for DunningRun entities
//!
//! Originally generated by metaphor-schema; now user-owned — declared under user_owned in
//! metaphor.codegen.yaml. The custom methods below hold the dunning SQL (4-layer rule).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DunningRun, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::DunningRun;

/// Table name for DunningRun entities
pub const TABLE_NAME: &str = "payment.dunning_runs";

/// Repository for DunningRun entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DunningRunRepository(
    backbone_orm::GenericCrudRepository<DunningRun, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DunningRunRepository {
    type Target = backbone_orm::GenericCrudRepository<DunningRun, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DunningRunRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Dunning-run SQL. Lives here (not in the service) per the module's 4-layer rule: services
/// orchestrate and own the unit of work, repositories hold the SQL.
impl DunningRunRepository {
    /// Insert one dunning run in `completed` status and return its id.
    ///
    /// Takes the CALLER'S connection so the run and its actions commit as one unit. The caller has
    /// already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_run(
        &self,
        conn: &mut PgConnection,
        id: Uuid,
        company_id: Uuid,
        as_of: NaiveDate,
        direction: &str,
    ) -> Result<Uuid, sqlx::Error> {
        let run_id = sqlx::query_scalar(
            r#"INSERT INTO payment.dunning_runs (id, company_id, as_of_date, direction, status)
               VALUES ($1, $2, $3, $4, 'completed'::dunning_run_status) RETURNING id"#,
        )
        .bind(id).bind(company_id).bind(as_of).bind(direction)
        .fetch_one(conn).await?;
        Ok(run_id)
    }

    /// Persist the count of actions the run actually emitted (gated on the `DO NOTHING` fence in
    /// [`DunningActionRepository::upsert_action`]). Same tx-binding contract as
    /// [`Self::insert_run`].
    pub async fn set_actions_emitted(
        &self,
        conn: &mut PgConnection,
        run_id: Uuid,
        actions_emitted: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE payment.dunning_runs SET actions_emitted = $2 WHERE id = $1")
            .bind(run_id).bind(actions_emitted)
            .execute(conn).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(DunningRunRepository, DunningRun, soft_delete);
