//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod mode_of_payment_repository;
mod payment_entry_repository;
mod payment_allocation_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use mode_of_payment_repository::ModeOfPaymentRepository;
pub use payment_entry_repository::PaymentEntryRepository;
pub use payment_allocation_repository::PaymentAllocationRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
