//! Repository for ModeOfPayment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ModeOfPayment, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ModeOfPayment;

/// Table name for ModeOfPayment entities
pub const TABLE_NAME: &str = "payment.mode_of_payments";

/// Repository for ModeOfPayment entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ModeOfPaymentRepository(
    backbone_orm::GenericCrudRepository<ModeOfPayment, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ModeOfPaymentRepository {
    type Target = backbone_orm::GenericCrudRepository<ModeOfPayment, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ModeOfPaymentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ModeOfPaymentRepository, ModeOfPayment, soft_delete);
