//! Repository for PaymentEntry entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written payment-entry SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;
// The multi-row and scalar read twins live only in the legacy `company_scope` module. Their
// connection discipline is what this repository needs — request-dedicated connection when the
// composing service bound one, plain pool otherwise. The helper's legacy task-local branch is
// never taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::{
    fetch_one_row_scoped, fetch_one_scalar_scoped, fetch_optional_scoped,
};

use crate::domain::entity::PaymentEntry;

/// Table name for PaymentEntry entities
pub const TABLE_NAME: &str = "payment.payment_entries";

/// Repository for PaymentEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
///
/// Tenancy (ADR-0029): the module carries no tenancy of its own — the composing service's
/// tenancy decorator owns org scoping. No statement keys on a tenant column: reads and
/// standalone writes ride the request-dedicated connection when the composing service bound
/// one (carrying the decorator's fence variables), plainly on the pool otherwise; write
/// transactions relay the caller's AMBIENT org scope (`org_scope::bind_org_scope_on`) in the
/// service before any statement. An undecorated deployment gets an unfenced module.
pub struct PaymentEntryRepository(
    backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PaymentEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a payment creation writes.
///
/// Mirrors the raw column shape rather than the `PaymentEntry` entity: `payment_type`/`party_type` bind
/// as `&str` with a DB-side cast (`$5::payment_type`, `$6::payment_party_type`) so a bad value fails as
/// a DB error rather than a deserialize panic, and `status`/`posting_state` are fixed to
/// `'draft'`/`'pending'` by the SQL. The money fields are already rounded by the service.
pub struct NewPaymentEntryRow<'a> {
    pub id: Uuid,
    pub payment_number: &'a str,
    pub branch_id: Option<Uuid>,
    pub payment_type: &'a str,
    pub party_type: Option<&'a str>,
    pub party_id: Option<Uuid>,
    pub posting_date: chrono::NaiveDate,
    pub currency: &'a str,
    pub mode_of_payment_id: Option<Uuid>,
    pub method: &'a str,
    pub provider_txn_id: Option<Uuid>,
    pub paid_amount: Decimal,
    pub allocated_amount: Decimal,
    pub unallocated_amount: Decimal,
    pub bank_account_id: Uuid,
    pub party_account_id: Uuid,
    pub reference_no: Option<&'a str>,
    pub withholding_amount: Decimal,
    pub withholding_account_id: Option<Uuid>,
    pub withholding_tax_type: &'a str,
}

/// Everything the settlement-post builder needs about a payment entry.
pub struct PostSourceRow {
    pub payment_number: String,
    pub branch_id: Option<Uuid>,
    pub payment_type: String,
    pub party_type: Option<String>,
    pub party_id: Option<Uuid>,
    pub posting_date: chrono::NaiveDate,
    pub currency: String,
    pub method: String,
    /// The fused status — the pre-sink gate reads it so a terminal payment refuses BEFORE the GL
    /// sink is driven (the CAS alone would refuse only after the journal existed).
    pub status: String,
    pub paid_amount: Decimal,
    pub bank_account_id: Uuid,
    pub party_account_id: Uuid,
    pub withholding_amount: Decimal,
    pub withholding_account_id: Option<Uuid>,
}

/// A payment's posted state, as the post short-circuit reads it.
pub struct PostedStateRow {
    pub posting_state: String,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
}

/// The header the `PaymentSettled` emission reads: the on-account remainder decides whether a
/// `PaymentReceivedOnAccount` also fires.
pub struct SettledHeaderRow {
    pub payment_type: String,
    pub party_id: Option<Uuid>,
    pub paid_amount: Decimal,
    pub unallocated_amount: Decimal,
}

/// The minimal header the outbox stage / cancel emission reads.
pub struct PaymentTypeAmountRow {
    pub payment_type: String,
    pub paid_amount: Decimal,
}

/// Hand-written payment-entry SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl PaymentEntryRepository {
    /// Insert a payment entry in `draft`/`pending`.
    ///
    /// Takes the CALLER'S connection so the entry and its allocations commit as one unit — a payment is
    /// never persisted without the allocations that satisfy `Σ allocations ≤ paid_amount`. The caller has
    /// already relayed the ambient org scope onto it (`org_scope::bind_org_scope_on`) — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a re-used payment number into a domain error.
    pub async fn insert_entry(
        &self,
        conn: &mut sqlx::PgConnection,
        p: &NewPaymentEntryRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO payment.payment_entries
                (id, payment_number, branch_id, payment_type, party_type, party_id,
                 posting_date, currency, mode_of_payment_id, method, provider_txn_id, paid_amount,
                 allocated_amount, unallocated_amount, bank_account_id, party_account_id, status,
                 posting_state, reference_no, withholding_amount, withholding_account_id, withholding_tax_type)
               VALUES ($1,$2,$3,$4::payment_type,$5::payment_party_type,$6,$7,$8,$9,$10::payment_method,$11,
                       $12,$13,$14,$15,$16,
                       'draft'::payment_status,'pending'::gl_posting_state,$17,$18,$19,$20::withholding_tax_type)"#,
        )
        .bind(p.id).bind(p.payment_number).bind(p.branch_id).bind(p.payment_type)
        .bind(p.party_type).bind(p.party_id).bind(p.posting_date).bind(p.currency).bind(p.mode_of_payment_id)
        .bind(p.method).bind(p.provider_txn_id)
        .bind(p.paid_amount).bind(p.allocated_amount).bind(p.unallocated_amount).bind(p.bank_account_id)
        .bind(p.party_account_id).bind(p.reference_no)
        .bind(p.withholding_amount).bind(p.withholding_account_id).bind(p.withholding_tax_type)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the payment the settlement post is built from.
    ///
    /// ID-only: no tenant argument. `fetch_optional_row_scoped` rides the request-dedicated
    /// connection when the composing service bound one — carrying the decorator's fence
    /// variables, so another unit's payment simply is not found — and runs plainly on the pool
    /// otherwise (an undecorated deployment is unfenced by design).
    pub async fn fetch_post_source(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<Option<PostSourceRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT payment_number, branch_id, payment_type::text AS pt, party_type::text AS party_t,
                          party_id, posting_date, currency, method::text AS m, status::text AS st,
                          paid_amount, bank_account_id, party_account_id, withholding_amount, withholding_account_id
                   FROM payment.payment_entries WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(payment_id),
        )
        .await?;
        Ok(row.map(|p| PostSourceRow {
            payment_number: p.get("payment_number"),
            branch_id: p.get("branch_id"),
            payment_type: p.get("pt"),
            party_type: p.get("party_t"),
            party_id: p.get("party_id"),
            posting_date: p.get("posting_date"),
            currency: p.get("currency"),
            method: p.get("m"),
            status: p.get("st"),
            paid_amount: p.get("paid_amount"),
            bank_account_id: p.get("bank_account_id"),
            party_account_id: p.get("party_account_id"),
            withholding_amount: p.get("withholding_amount"),
            withholding_account_id: p.get("withholding_account_id"),
        }))
    }

    /// Read the post this payment's ORIGINAL settlement produced — the reversal links back to it via
    /// `reverses_post_id`. Same ID-only scope contract as [`Self::fetch_post_source`].
    pub async fn fetch_accounting_post_id(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT accounting_post_id FROM payment.payment_entries WHERE id=$1",
            )
            .bind(payment_id),
        )
        .await
    }

    /// Read a payment's posted state, for the post short-circuit. Same ID-only scope contract as
    /// [`Self::fetch_post_source`].
    pub async fn fetch_posted_state(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<Option<PostedStateRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT posting_state::text AS ps, journal_id, accounting_post_id FROM payment.payment_entries WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(payment_id),
        )
        .await?;
        Ok(row.map(|r| PostedStateRow {
            posting_state: r.get("ps"),
            journal_id: r.get("journal_id"),
            accounting_post_id: r.get("accounting_post_id"),
        }))
    }

    /// Read a payment's status and GL posting state — the pair the reverse gate keys on (status
    /// alone cannot tell a landed-but-gl-broken entry from a truly reversible one). Same ID-only
    /// scope contract as [`Self::fetch_post_source`].
    pub async fn fetch_status(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<Option<(String, String)>, sqlx::Error> {
        fetch_optional_scoped(
            pool,
            sqlx::query_as::<_, (String, String)>(
                "SELECT status::text, posting_state::text FROM payment.payment_entries WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(payment_id),
        )
        .await
    }

    /// Perform the pending|failed→posted transition, landing the fused status (`in_flight` or
    /// `paid` — the caller computed which via `landing_state`). Returns the rows affected: the
    /// caller gates the reconcile and the `PaymentSettled` seam event on this being 1, because the
    /// seam routes into `billing::apply_settlement` — a double-emit would draw an invoice's
    /// outstanding down twice. The CAS covers both columns: only a pending-or-failed (retry after a
    /// GL rejection), not-yet-landed entry transitions — a rejected or already-landed payment
    /// matches zero rows.
    ///
    /// Takes the CALLER'S connection so this transition and the durable outbox stage commit as ONE unit;
    /// a crash after the transition can then never lose the event. The caller has already relayed the
    /// ambient org scope onto it (`org_scope::bind_org_scope_on`) — don't re-bind here.
    pub async fn mark_posted(
        &self,
        conn: &mut sqlx::PgConnection,
        payment_id: Uuid,
        journal_id: Uuid,
        accounting_post_id: Uuid,
        new_status: &str,
    ) -> Result<u64, sqlx::Error> {
        let res = sqlx::query(
            r#"UPDATE payment.payment_entries SET posting_state='posted'::gl_posting_state,
                status=$4::payment_status, journal_id=$2, accounting_post_id=$3, posted_at=now()
               WHERE id=$1 AND posting_state IN ('pending'::gl_posting_state, 'failed'::gl_posting_state)
                 AND status IN ('draft'::payment_status, 'submitted'::payment_status)"#,
        )
        .bind(payment_id).bind(journal_id).bind(accounting_post_id).bind(new_status)
        .execute(conn)
        .await?;
        Ok(res.rows_affected())
    }

    /// Perform the draft→submitted transition (the `submit` verb). Returns the rows affected: 0 means
    /// the CAS refused (already submitted, landed, or terminal). Fenced by the ambient org scope.
    pub async fn mark_submitted(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let res = org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE payment.payment_entries SET status='submitted'::payment_status WHERE id=$1 AND status='draft'::payment_status")
                .bind(payment_id),
        )
        .await?;
        Ok(res.rows_affected())
    }

    /// Perform the submitted→rejected transition (the `reject` verb, terminal — the PRE-settlement
    /// stop: nothing has committed, so rejecting is a pure label flip). An in_flight or paid entry
    /// HAS a committed journal and a billing knock-off; its exit is `reverse_payment` (which unwinds
    /// the GL and restores the invoices), never reject — a rejected-from-in_flight entry would
    /// strand its journal with no verb left that could remove it. Returns the rows affected: 0 means
    /// the CAS refused (draft, landed, or terminal). Fenced by the ambient org scope.
    pub async fn mark_rejected(&self, pool: &PgPool, payment_id: Uuid) -> Result<u64, sqlx::Error> {
        let res = org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE payment.payment_entries SET status='rejected'::payment_status WHERE id=$1 AND status='submitted'::payment_status")
                .bind(payment_id),
        )
        .await?;
        Ok(res.rows_affected())
    }

    /// Perform the in_flight→paid drift — the bank-confirmation landing. This is the ONLY writer of
    /// that transition (the `confirm_cash_once` consumer on `BankClearanceRecorded`); a hand verb
    /// cannot reach it. Returns the rows affected: 0 from any other state is the documented no-op,
    /// not an error (the event may legitimately arrive for an already-paid or never-in-flight
    /// payment). Takes the CALLER'S connection so the drift and the inbox dedup commit as one unit.
    pub async fn confirm_cash_on(
        &self,
        conn: &mut sqlx::PgConnection,
        payment_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let res = sqlx::query(
            "UPDATE payment.payment_entries SET status='paid'::payment_status WHERE id=$1 AND status='in_flight'::payment_status",
        )
        .bind(payment_id)
        .execute(conn)
        .await?;
        Ok(res.rows_affected())
    }

    /// Record that the ledger rejected this post. CAS-guarded on `posting_state`: a `failed` stamp
    /// may only land on a pending-or-failed entry — never over a committed `posted`. Without the
    /// guard, a spurious sink error (transport timeout AFTER the GL committed) in a concurrent
    /// retry would overwrite the live `posted` truth, and the entry would enter a state no verb can
    /// exit (reverse's journal would post while `mark_cancelled` matches zero rows). Fenced by the
    /// ambient org scope. The caller also deliberately IGNORES the result — the GL rejection is the
    /// error being reported, and failing to mark it must not mask that.
    pub async fn mark_failed(&self, pool: &PgPool, payment_id: Uuid) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE payment.payment_entries SET posting_state='failed'::gl_posting_state WHERE id=$1 AND posting_state IN ('pending'::gl_posting_state, 'failed'::gl_posting_state)")
                .bind(payment_id),
        )
        .await?;
        Ok(())
    }

    /// Perform the in_flight|paid→cancelled transition. Returns the rows affected: the caller gates the
    /// `PaymentCancelled` emission on this being 1, so the reverse-seam restores each invoice exactly
    /// once even under a repeat/concurrent reverse. The CAS keys on `posting_state` (the GL-sync
    /// truth): only an entry whose post actually committed can be cancelled — a draft/submitted/
    /// rejected payment matches zero rows. Fenced by the ambient org scope.
    pub async fn mark_cancelled(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let res = org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE payment.payment_entries SET status='cancelled'::payment_status WHERE id=$1 AND posting_state='posted'::gl_posting_state AND status IN ('in_flight'::payment_status, 'paid'::payment_status)")
                .bind(payment_id),
        )
        .await?;
        Ok(res.rows_affected())
    }

    /// Read the header the `PaymentSettled` emission needs. Same ID-only scope contract as
    /// [`Self::fetch_post_source`].
    pub async fn fetch_settled_header(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<SettledHeaderRow, sqlx::Error> {
        let hdr = fetch_one_row_scoped(
            pool,
            sqlx::query("SELECT payment_type::text AS pt, party_id, paid_amount, unallocated_amount FROM payment.payment_entries WHERE id=$1")
                .bind(payment_id),
        )
        .await?;
        Ok(SettledHeaderRow {
            payment_type: hdr.get("pt"),
            party_id: hdr.get("party_id"),
            paid_amount: hdr.get("paid_amount"),
            unallocated_amount: hdr.get("unallocated_amount"),
        })
    }

    /// Read the minimal header the `PaymentCancelled` emission needs. Same ID-only scope contract as
    /// [`Self::fetch_post_source`].
    pub async fn fetch_type_and_amount(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<PaymentTypeAmountRow, sqlx::Error> {
        let hdr = fetch_one_row_scoped(
            pool,
            sqlx::query("SELECT payment_type::text AS pt, paid_amount FROM payment.payment_entries WHERE id=$1")
                .bind(payment_id),
        )
        .await?;
        Ok(PaymentTypeAmountRow {
            payment_type: hdr.get("pt"),
            paid_amount: hdr.get("paid_amount"),
        })
    }

    /// Read the same minimal header on the CALLER'S transaction, so the outbox stage reads the payment
    /// on the SAME tx as the posted-transition it is atomic with.
    pub async fn fetch_type_and_amount_on(
        &self,
        conn: &mut sqlx::PgConnection,
        payment_id: Uuid,
    ) -> Result<PaymentTypeAmountRow, sqlx::Error> {
        let hdr = sqlx::query(
            "SELECT payment_type::text AS pt, paid_amount FROM payment.payment_entries WHERE id=$1",
        )
        .bind(payment_id)
        .fetch_one(conn)
        .await?;
        Ok(PaymentTypeAmountRow {
            payment_type: hdr.get("pt"),
            paid_amount: hdr.get("paid_amount"),
        })
    }
}

backbone_core::impl_crud_repository!(PaymentEntryRepository, PaymentEntry, soft_delete);
