//! Repository for PaymentEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PaymentEntry;

/// Table name for PaymentEntry entities
pub const TABLE_NAME: &str = "payment.payment_entries";

/// Repository for PaymentEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PaymentEntryRepository(
    backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PaymentEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PaymentEntryRepository, PaymentEntry, soft_delete);
