//! Repository for PaymentAllocation entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written allocation SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentAllocation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PaymentAllocation;

/// Table name for PaymentAllocation entities
pub const TABLE_NAME: &str = "payment.payment_allocations";

/// Repository for PaymentAllocation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PaymentAllocationRepository(
    backbone_orm::GenericCrudRepository<PaymentAllocation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentAllocationRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentAllocation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PaymentAllocationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an allocation writes. Mirrors the raw column shape rather than the `PaymentAllocation`
/// entity: `invoice_kind` binds as `&str` with a DB-side cast (`$4::settlement_kind`), so an unknown
/// kind fails as a DB error rather than a deserialize panic.
pub struct NewAllocationRow<'a> {
    pub id: Uuid,
    pub payment_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: &'a str,
    pub allocated_amount: Decimal,
}

/// One allocation as the settled/cancelled seam events carry it — which invoice was knocked down, and
/// by how much.
pub struct AllocationRow {
    pub invoice_ref: Uuid,
    pub invoice_kind: String,
    pub allocated_amount: Decimal,
}

/// Hand-written allocation SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl PaymentAllocationRepository {
    /// Insert one allocation line.
    ///
    /// Takes the CALLER'S connection so the allocations and their payment entry commit as one unit. The
    /// caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_allocation(
        &self,
        conn: &mut sqlx::PgConnection,
        a: &NewAllocationRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO payment.payment_allocations
                (id, payment_id, invoice_ref, invoice_kind, allocated_amount)
               VALUES ($1,$2,$3,$4::settlement_kind,$5)"#,
        )
        .bind(a.id).bind(a.payment_id).bind(a.invoice_ref).bind(a.invoice_kind).bind(a.allocated_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a payment's allocations for the settled/cancelled seam events. Caller supplies the company
    /// scope.
    pub async fn fetch_for_payment(
        &self,
        pool: &PgPool,
        payment_id: Uuid,
    ) -> Result<Vec<AllocationRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query("SELECT invoice_ref, invoice_kind::text AS kind, allocated_amount FROM payment.payment_allocations WHERE payment_id=$1 AND (metadata->>'deleted_at') IS NULL")
                .bind(payment_id),
        )
        .await?;
        Ok(rows.iter().map(|r| AllocationRow {
            invoice_ref: r.get("invoice_ref"), invoice_kind: r.get("kind"),
            allocated_amount: r.get("allocated_amount"),
        }).collect())
    }

    /// Read the same allocations on the CALLER'S transaction, so the outbox stage reads them on the SAME
    /// tx as the posted-transition the staged event is atomic with.
    pub async fn fetch_for_payment_on(
        &self,
        conn: &mut sqlx::PgConnection,
        payment_id: Uuid,
    ) -> Result<Vec<AllocationRow>, sqlx::Error> {
        let rows = sqlx::query("SELECT invoice_ref, invoice_kind::text AS kind, allocated_amount FROM payment.payment_allocations WHERE payment_id=$1 AND (metadata->>'deleted_at') IS NULL")
            .bind(payment_id)
            .fetch_all(conn)
            .await?;
        Ok(rows.iter().map(|r| AllocationRow {
            invoice_ref: r.get("invoice_ref"), invoice_kind: r.get("kind"),
            allocated_amount: r.get("allocated_amount"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(PaymentAllocationRepository, PaymentAllocation, soft_delete);
