//! Validator for ModeOfPayment entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ModeOfPayment>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ModeOfPayment;

/// Validator type alias for ModeOfPayment entities.
pub type ModeOfPaymentValidator = EntityValidator<ModeOfPayment>;

/// Build a validator for ModeOfPayment with all schema-defined field rules.
pub fn mode_of_payment_validator() -> ModeOfPaymentValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &ModeOfPayment| &e.code))
        .rule(RequiredString::new("name", |e: &ModeOfPayment| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
