//! Validator for PaymentEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::PaymentEntry;

/// Validator type alias for PaymentEntry entities.
pub type PaymentEntryValidator = EntityValidator<PaymentEntry>;

/// Build a validator for PaymentEntry with all schema-defined field rules.
pub fn payment_entry_validator() -> PaymentEntryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("payment_number", |e: &PaymentEntry| &e.payment_number))
        .rule(RequiredString::new("currency", |e: &PaymentEntry| &e.currency))
        .rule(OptionalNotBlank::new("reference_no", |e: &PaymentEntry| e.reference_no.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &PaymentEntry| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
