//! Validator for PaymentAllocation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentAllocation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use crate::domain::entity::PaymentAllocation;
use backbone_core::NonNegative;
use backbone_core::{EntityValidator, ValidationError, ValidationErrors};

/// Validator type alias for PaymentAllocation entities.
pub type PaymentAllocationValidator = EntityValidator<PaymentAllocation>;

/// Build a validator for PaymentAllocation with all schema-defined field rules.
pub fn payment_allocation_validator() -> PaymentAllocationValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
    // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
