//! Auth configuration for AgingSnapshot handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AgingSnapshot>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AgingSnapshotService;
use crate::domain::entity::AgingSnapshot;

/// Permission string constants for AgingSnapshot operations.
pub mod permissions {
    pub const LIST:        &str = "aging_snapshot:list";
    pub const READ:        &str = "aging_snapshot:read";
    pub const CREATE:      &str = "aging_snapshot:create";
    pub const UPDATE:      &str = "aging_snapshot:update";
    pub const DELETE:      &str = "aging_snapshot:delete";
    pub const RESTORE:     &str = "aging_snapshot:restore";
    pub const TRASH:       &str = "aging_snapshot:trash";
    pub const EMPTY_TRASH: &str = "aging_snapshot:empty_trash";
    pub const BULK_CREATE: &str = "aging_snapshot:bulk_create";
    pub const UPSERT:      &str = "aging_snapshot:upsert";
}

/// Resource policy for AgingSnapshot — maps CRUD actions to permission strings.
pub struct AgingSnapshotPolicy;

#[async_trait]
impl ResourcePolicy<AgingSnapshot> for AgingSnapshotPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AgingSnapshot,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AgingSnapshot handlers.
///
/// Wraps `AgingSnapshotService` and checks `AgingSnapshotPolicy` before delegating.
pub type AgingSnapshotGuard = PermissionGuard<AgingSnapshot>;

/// Service-integrated permission guard for AgingSnapshot (for use in generated handlers).
pub type AgingSnapshotServiceGuard = ServicePermissionGuard<AgingSnapshot, AgingSnapshotService, AgingSnapshotPolicy>;

// <<< CUSTOM
// END CUSTOM
