//! Auth configuration for DunningRun handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<DunningRun>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DunningRunService;
use crate::domain::entity::DunningRun;

/// Permission string constants for DunningRun operations.
pub mod permissions {
    pub const LIST:        &str = "dunning_run:list";
    pub const READ:        &str = "dunning_run:read";
    pub const CREATE:      &str = "dunning_run:create";
    pub const UPDATE:      &str = "dunning_run:update";
    pub const DELETE:      &str = "dunning_run:delete";
    pub const RESTORE:     &str = "dunning_run:restore";
    pub const TRASH:       &str = "dunning_run:trash";
    pub const EMPTY_TRASH: &str = "dunning_run:empty_trash";
    pub const BULK_CREATE: &str = "dunning_run:bulk_create";
    pub const UPSERT:      &str = "dunning_run:upsert";
}

/// Resource policy for DunningRun — maps CRUD actions to permission strings.
pub struct DunningRunPolicy;

#[async_trait]
impl ResourcePolicy<DunningRun> for DunningRunPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &DunningRun,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for DunningRun handlers.
///
/// Wraps `DunningRunService` and checks `DunningRunPolicy` before delegating.
pub type DunningRunGuard = PermissionGuard<DunningRun>;

/// Service-integrated permission guard for DunningRun (for use in generated handlers).
pub type DunningRunServiceGuard = ServicePermissionGuard<DunningRun, DunningRunService, DunningRunPolicy>;

// <<< CUSTOM
// END CUSTOM
