//! Auth configuration for DunningAction handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<DunningAction>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DunningActionService;
use crate::domain::entity::DunningAction;

/// Permission string constants for DunningAction operations.
pub mod permissions {
    pub const LIST:        &str = "dunning_action:list";
    pub const READ:        &str = "dunning_action:read";
    pub const CREATE:      &str = "dunning_action:create";
    pub const UPDATE:      &str = "dunning_action:update";
    pub const DELETE:      &str = "dunning_action:delete";
    pub const RESTORE:     &str = "dunning_action:restore";
    pub const TRASH:       &str = "dunning_action:trash";
    pub const EMPTY_TRASH: &str = "dunning_action:empty_trash";
    pub const BULK_CREATE: &str = "dunning_action:bulk_create";
    pub const UPSERT:      &str = "dunning_action:upsert";
}

/// Resource policy for DunningAction — maps CRUD actions to permission strings.
pub struct DunningActionPolicy;

#[async_trait]
impl ResourcePolicy<DunningAction> for DunningActionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &DunningAction,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for DunningAction handlers.
///
/// Wraps `DunningActionService` and checks `DunningActionPolicy` before delegating.
pub type DunningActionGuard = PermissionGuard<DunningAction>;

/// Service-integrated permission guard for DunningAction (for use in generated handlers).
pub type DunningActionServiceGuard = ServicePermissionGuard<DunningAction, DunningActionService, DunningActionPolicy>;

// <<< CUSTOM
// END CUSTOM
