//! Auth configuration for ModeOfPayment handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ModeOfPayment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ModeOfPaymentService;
use crate::domain::entity::ModeOfPayment;

/// Permission string constants for ModeOfPayment operations.
pub mod permissions {
    pub const LIST:        &str = "mode_of_payment:list";
    pub const READ:        &str = "mode_of_payment:read";
    pub const CREATE:      &str = "mode_of_payment:create";
    pub const UPDATE:      &str = "mode_of_payment:update";
    pub const DELETE:      &str = "mode_of_payment:delete";
    pub const RESTORE:     &str = "mode_of_payment:restore";
    pub const TRASH:       &str = "mode_of_payment:trash";
    pub const EMPTY_TRASH: &str = "mode_of_payment:empty_trash";
    pub const BULK_CREATE: &str = "mode_of_payment:bulk_create";
    pub const UPSERT:      &str = "mode_of_payment:upsert";
}

/// Resource policy for ModeOfPayment — maps CRUD actions to permission strings.
pub struct ModeOfPaymentPolicy;

#[async_trait]
impl ResourcePolicy<ModeOfPayment> for ModeOfPaymentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ModeOfPayment,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ModeOfPayment handlers.
///
/// Wraps `ModeOfPaymentService` and checks `ModeOfPaymentPolicy` before delegating.
pub type ModeOfPaymentGuard = PermissionGuard<ModeOfPayment>;

/// Service-integrated permission guard for ModeOfPayment (for use in generated handlers).
pub type ModeOfPaymentServiceGuard = ServicePermissionGuard<ModeOfPayment, ModeOfPaymentService, ModeOfPaymentPolicy>;

// <<< CUSTOM
// END CUSTOM
