//! Auth configuration for PaymentEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PaymentEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PaymentEntryService;
use crate::domain::entity::PaymentEntry;

/// Permission string constants for PaymentEntry operations.
pub mod permissions {
    pub const LIST:        &str = "payment_entry:list";
    pub const READ:        &str = "payment_entry:read";
    pub const CREATE:      &str = "payment_entry:create";
    pub const UPDATE:      &str = "payment_entry:update";
    pub const DELETE:      &str = "payment_entry:delete";
    pub const RESTORE:     &str = "payment_entry:restore";
    pub const TRASH:       &str = "payment_entry:trash";
    pub const EMPTY_TRASH: &str = "payment_entry:empty_trash";
    pub const BULK_CREATE: &str = "payment_entry:bulk_create";
    pub const UPSERT:      &str = "payment_entry:upsert";
}

/// Resource policy for PaymentEntry — maps CRUD actions to permission strings.
pub struct PaymentEntryPolicy;

#[async_trait]
impl ResourcePolicy<PaymentEntry> for PaymentEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PaymentEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PaymentEntry handlers.
///
/// Wraps `PaymentEntryService` and checks `PaymentEntryPolicy` before delegating.
pub type PaymentEntryGuard = PermissionGuard<PaymentEntry>;

/// Service-integrated permission guard for PaymentEntry (for use in generated handlers).
pub type PaymentEntryServiceGuard = ServicePermissionGuard<PaymentEntry, PaymentEntryService, PaymentEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
