//! Auth configuration for PaymentAllocation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PaymentAllocation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PaymentAllocationService;
use crate::domain::entity::PaymentAllocation;

/// Permission string constants for PaymentAllocation operations.
pub mod permissions {
    pub const LIST:        &str = "payment_allocation:list";
    pub const READ:        &str = "payment_allocation:read";
    pub const CREATE:      &str = "payment_allocation:create";
    pub const UPDATE:      &str = "payment_allocation:update";
    pub const DELETE:      &str = "payment_allocation:delete";
    pub const RESTORE:     &str = "payment_allocation:restore";
    pub const TRASH:       &str = "payment_allocation:trash";
    pub const EMPTY_TRASH: &str = "payment_allocation:empty_trash";
    pub const BULK_CREATE: &str = "payment_allocation:bulk_create";
    pub const UPSERT:      &str = "payment_allocation:upsert";
}

/// Resource policy for PaymentAllocation — maps CRUD actions to permission strings.
pub struct PaymentAllocationPolicy;

#[async_trait]
impl ResourcePolicy<PaymentAllocation> for PaymentAllocationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PaymentAllocation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PaymentAllocation handlers.
///
/// Wraps `PaymentAllocationService` and checks `PaymentAllocationPolicy` before delegating.
pub type PaymentAllocationGuard = PermissionGuard<PaymentAllocation>;

/// Service-integrated permission guard for PaymentAllocation (for use in generated handlers).
pub type PaymentAllocationServiceGuard = ServicePermissionGuard<PaymentAllocation, PaymentAllocationService, PaymentAllocationPolicy>;

// <<< CUSTOM
// END CUSTOM
