//! DunningRun API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the DunningRun CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DUNNINGRUN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for DunningRun
pub struct DunningRunTestData;

impl TestDataGenerator for DunningRunTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "as_of_date": Utc::now().format("%Y-%m-%d").to_string(),
            "direction": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "snapshot_id": null,
            "actions_emitted": 1,
            "status": "building",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "as_of_date": Utc::now().format("%Y-%m-%d").to_string(),
            "direction": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "snapshot_id": null,
            "actions_emitted": 1,
            "status": "building",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// DUNNINGRUN API TEST
// ============================================================================

/// DunningRun API test suite
pub struct DunningRunApiTest {
    inner: GenericCrudTest<DunningRunTestData>,
}

impl DunningRunApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/dunning_runs", "DunningRun");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DunningRunTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DunningRunApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_dunning_run_crud() {
        let mut test = DunningRunApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add DunningRun specific tests here
// <<< CUSTOM TESTS END >>>
