//! DunningAction API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the DunningAction CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DUNNINGACTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for DunningAction
pub struct DunningActionTestData;

impl TestDataGenerator for DunningActionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "run_id": Uuid::new_v4().to_string(),
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_id": null,
            "level": "current",
            "action_type": "send_reminder",
            "days_past_due": 1,
            "outstanding_amount": 0,
            "status": "pending",
            "processed_at": now,
            "result_ref": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "run_id": Uuid::new_v4().to_string(),
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_id": null,
            "level": "current",
            "action_type": "send_reminder",
            "days_past_due": 1,
            "outstanding_amount": 0,
            "status": "pending",
            "processed_at": now,
            "result_ref": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/dunning_runs", &super::dunning_run_api_test::DunningRunTestData).await {
            deps.push(("run_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// DUNNINGACTION API TEST
// ============================================================================

/// DunningAction API test suite
pub struct DunningActionApiTest {
    inner: GenericCrudTest<DunningActionTestData>,
}

impl DunningActionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/dunning_actions", "DunningAction");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DunningActionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DunningActionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_dunning_action_crud() {
        let mut test = DunningActionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add DunningAction specific tests here
// <<< CUSTOM TESTS END >>>
