//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod mode_of_payment_api_test;
pub mod payment_entry_api_test;
pub mod payment_allocation_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use mode_of_payment_api_test::*;
pub use payment_entry_api_test::*;
pub use payment_allocation_api_test::*;
