//! ModeOfPayment API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ModeOfPayment CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MODEOFPAYMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ModeOfPayment
pub struct ModeOfPaymentTestData;

impl TestDataGenerator for ModeOfPaymentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mode_type": "cash",
            "default_account_id": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mode_type": "cash",
            "default_account_id": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// MODEOFPAYMENT API TEST
// ============================================================================

/// ModeOfPayment API test suite
pub struct ModeOfPaymentApiTest {
    inner: GenericCrudTest<ModeOfPaymentTestData>,
}

impl ModeOfPaymentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/mode_of_payments", "ModeOfPayment");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ModeOfPaymentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ModeOfPaymentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_mode_of_payment_crud() {
        let mut test = ModeOfPaymentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ModeOfPayment specific tests here
// <<< CUSTOM TESTS END >>>
