//! PaymentEntry API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PaymentEntry CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PAYMENTENTRY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PaymentEntry
pub struct PaymentEntryTestData;

impl TestDataGenerator for PaymentEntryTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "payment_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "payment_type": "receive",
            "party_type": null,
            "party_id": null,
            "posting_date": Utc::now().format("%Y-%m-%d").to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mode_of_payment_id": null,
            "paid_amount": 0,
            "allocated_amount": 0,
            "unallocated_amount": 0,
            "bank_account_id": Uuid::new_v4().to_string(),
            "party_account_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "posting_state": "pending",
            "journal_id": null,
            "accounting_post_id": null,
            "posted_at": now,
            "reference_no": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "payment_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "payment_type": "receive",
            "party_type": null,
            "party_id": null,
            "posting_date": Utc::now().format("%Y-%m-%d").to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mode_of_payment_id": null,
            "paid_amount": 0,
            "allocated_amount": 0,
            "unallocated_amount": 0,
            "bank_account_id": Uuid::new_v4().to_string(),
            "party_account_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "posting_state": "pending",
            "journal_id": null,
            "accounting_post_id": null,
            "posted_at": now,
            "reference_no": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PAYMENTENTRY API TEST
// ============================================================================

/// PaymentEntry API test suite
pub struct PaymentEntryApiTest {
    inner: GenericCrudTest<PaymentEntryTestData>,
}

impl PaymentEntryApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/payment_entries", "PaymentEntry");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PaymentEntryTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PaymentEntryApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_payment_entry_crud() {
        let mut test = PaymentEntryApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PaymentEntry specific tests here
// <<< CUSTOM TESTS END >>>
