//! Payment Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ModeOfPaymentService;
use crate::application::service::PaymentEntryService;
use crate::application::service::PaymentAllocationService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ModeOfPayment service
    pub mode_of_payment_service: Arc<ModeOfPaymentService>,
    /// PaymentEntry service
    pub payment_entry_service: Arc<PaymentEntryService>,
    /// PaymentAllocation service
    pub payment_allocation_service: Arc<PaymentAllocationService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        mode_of_payment_service: Arc<ModeOfPaymentService>,
        payment_entry_service: Arc<PaymentEntryService>,
        payment_allocation_service: Arc<PaymentAllocationService>
    ) -> Self {
        Self {
            mode_of_payment_service,
            payment_entry_service,
            payment_allocation_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PaymentModule) -> Self {
        Self {
            mode_of_payment_service: module.mode_of_payment_service.clone(),
            payment_entry_service: module.payment_entry_service.clone(),
            payment_allocation_service: module.payment_allocation_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    mode_of_payment_service: Option<Arc<ModeOfPaymentService>>,
    payment_entry_service: Option<Arc<PaymentEntryService>>,
    payment_allocation_service: Option<Arc<PaymentAllocationService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ModeOfPayment service.
    pub fn with_mode_of_payment_service(mut self, service: Arc<ModeOfPaymentService>) -> Self {
        self.mode_of_payment_service = Some(service);
        self
    }

    /// Set the PaymentEntry service.
    pub fn with_payment_entry_service(mut self, service: Arc<PaymentEntryService>) -> Self {
        self.payment_entry_service = Some(service);
        self
    }

    /// Set the PaymentAllocation service.
    pub fn with_payment_allocation_service(mut self, service: Arc<PaymentAllocationService>) -> Self {
        self.payment_allocation_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            mode_of_payment_service: self.mode_of_payment_service.expect("mode_of_payment_service is required"),
            payment_entry_service: self.payment_entry_service.expect("payment_entry_service is required"),
            payment_allocation_service: self.payment_allocation_service.expect("payment_allocation_service is required"),
        }
    }
}
