//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    aging_snapshot_handler::create_aging_snapshot_routes,
    aging_bucket_handler::create_aging_bucket_routes,
    dunning_run_handler::create_dunning_run_routes,
    dunning_action_handler::create_dunning_action_routes,
    mode_of_payment_handler::create_mode_of_payment_routes,
    payment_entry_handler::create_payment_entry_routes,
    payment_allocation_handler::create_payment_allocation_routes,
};

use crate::application::service::{
    AgingSnapshotService,
    AgingBucketService,
    DunningRunService,
    DunningActionService,
    ModeOfPaymentService,
    PaymentEntryService,
    PaymentAllocationService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub aging_snapshot: Arc<AgingSnapshotService>,
    pub aging_bucket: Arc<AgingBucketService>,
    pub dunning_run: Arc<DunningRunService>,
    pub dunning_action: Arc<DunningActionService>,
    pub mode_of_payment: Arc<ModeOfPaymentService>,
    pub payment_entry: Arc<PaymentEntryService>,
    pub payment_allocation: Arc<PaymentAllocationService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // AgingSnapshot routes (12 Backbone endpoints)
        .merge(create_aging_snapshot_routes(services.aging_snapshot))
        // AgingBucket routes (12 Backbone endpoints)
        .merge(create_aging_bucket_routes(services.aging_bucket))
        // DunningRun routes (12 Backbone endpoints)
        .merge(create_dunning_run_routes(services.dunning_run))
        // DunningAction routes (12 Backbone endpoints)
        .merge(create_dunning_action_routes(services.dunning_action))
        // ModeOfPayment routes (12 Backbone endpoints)
        .merge(create_mode_of_payment_routes(services.mode_of_payment))
        // PaymentEntry routes (12 Backbone endpoints)
        .merge(create_payment_entry_routes(services.payment_entry))
        // PaymentAllocation routes (12 Backbone endpoints)
        .merge(create_payment_allocation_routes(services.payment_allocation))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn aging_snapshot_routes(service: Arc<AgingSnapshotService>) -> Router {
        create_aging_snapshot_routes(service)
    }

    pub fn aging_bucket_routes(service: Arc<AgingBucketService>) -> Router {
        create_aging_bucket_routes(service)
    }

    pub fn dunning_run_routes(service: Arc<DunningRunService>) -> Router {
        create_dunning_run_routes(service)
    }

    pub fn dunning_action_routes(service: Arc<DunningActionService>) -> Router {
        create_dunning_action_routes(service)
    }

    pub fn mode_of_payment_routes(service: Arc<ModeOfPaymentService>) -> Router {
        create_mode_of_payment_routes(service)
    }

    pub fn payment_entry_routes(service: Arc<PaymentEntryService>) -> Router {
        create_payment_entry_routes(service)
    }

    pub fn payment_allocation_routes(service: Arc<PaymentAllocationService>) -> Router {
        create_payment_allocation_routes(service)
    }

}
