//! Public events for Payment module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// AGINGSNAPSHOT EVENTS
// ============================================================================

/// Event published when a AgingSnapshot is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotCreatedEvent {
    pub id: AgingSnapshotId,
    pub data: AgingSnapshotDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AgingSnapshot is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotUpdatedEvent {
    pub id: AgingSnapshotId,
    pub data: AgingSnapshotDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AgingSnapshot is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotDeletedEvent {
    pub id: AgingSnapshotId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// AGINGBUCKET EVENTS
// ============================================================================

/// Event published when a AgingBucket is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketCreatedEvent {
    pub id: AgingBucketId,
    pub data: AgingBucketDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AgingBucket is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketUpdatedEvent {
    pub id: AgingBucketId,
    pub data: AgingBucketDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AgingBucket is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketDeletedEvent {
    pub id: AgingBucketId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// DUNNINGRUN EVENTS
// ============================================================================

/// Event published when a DunningRun is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunCreatedEvent {
    pub id: DunningRunId,
    pub data: DunningRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DunningRun is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunUpdatedEvent {
    pub id: DunningRunId,
    pub data: DunningRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DunningRun is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunDeletedEvent {
    pub id: DunningRunId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// DUNNINGACTION EVENTS
// ============================================================================

/// Event published when a DunningAction is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionCreatedEvent {
    pub id: DunningActionId,
    pub data: DunningActionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DunningAction is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionUpdatedEvent {
    pub id: DunningActionId,
    pub data: DunningActionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DunningAction is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionDeletedEvent {
    pub id: DunningActionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODEOFPAYMENT EVENTS
// ============================================================================

/// Event published when a ModeOfPayment is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentCreatedEvent {
    pub id: ModeOfPaymentId,
    pub data: ModeOfPaymentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ModeOfPayment is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentUpdatedEvent {
    pub id: ModeOfPaymentId,
    pub data: ModeOfPaymentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ModeOfPayment is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentDeletedEvent {
    pub id: ModeOfPaymentId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PAYMENTENTRY EVENTS
// ============================================================================

/// Event published when a PaymentEntry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntryCreatedEvent {
    pub id: PaymentEntryId,
    pub data: PaymentEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentEntry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntryUpdatedEvent {
    pub id: PaymentEntryId,
    pub data: PaymentEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentEntry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntryDeletedEvent {
    pub id: PaymentEntryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PAYMENTALLOCATION EVENTS
// ============================================================================

/// Event published when a PaymentAllocation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationCreatedEvent {
    pub id: PaymentAllocationId,
    pub data: PaymentAllocationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentAllocation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationUpdatedEvent {
    pub id: PaymentAllocationId,
    pub data: PaymentAllocationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PaymentAllocation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationDeletedEvent {
    pub id: PaymentAllocationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Payment module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PaymentEvent {
    AgingSnapshotCreated(AgingSnapshotCreatedEvent),
    AgingSnapshotUpdated(AgingSnapshotUpdatedEvent),
    AgingSnapshotDeleted(AgingSnapshotDeletedEvent),
    AgingBucketCreated(AgingBucketCreatedEvent),
    AgingBucketUpdated(AgingBucketUpdatedEvent),
    AgingBucketDeleted(AgingBucketDeletedEvent),
    DunningRunCreated(DunningRunCreatedEvent),
    DunningRunUpdated(DunningRunUpdatedEvent),
    DunningRunDeleted(DunningRunDeletedEvent),
    DunningActionCreated(DunningActionCreatedEvent),
    DunningActionUpdated(DunningActionUpdatedEvent),
    DunningActionDeleted(DunningActionDeletedEvent),
    ModeOfPaymentCreated(ModeOfPaymentCreatedEvent),
    ModeOfPaymentUpdated(ModeOfPaymentUpdatedEvent),
    ModeOfPaymentDeleted(ModeOfPaymentDeletedEvent),
    PaymentEntryCreated(PaymentEntryCreatedEvent),
    PaymentEntryUpdated(PaymentEntryUpdatedEvent),
    PaymentEntryDeleted(PaymentEntryDeletedEvent),
    PaymentAllocationCreated(PaymentAllocationCreatedEvent),
    PaymentAllocationUpdated(PaymentAllocationUpdatedEvent),
    PaymentAllocationDeleted(PaymentAllocationDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PaymentEventMetadata {
    fn default() -> Self {
        Self {
            module: "payment",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
