//! Payment Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Payment exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use payment::exports::{AgingSnapshotDto, PaymentQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AgingSnapshotDto` - Data transfer object for AgingSnapshot
/// - `AgingSnapshotSummary` - Summary view of AgingSnapshot
/// - `AgingSnapshotId` - Type-safe ID wrapper
/// - `AgingBucketDto` - Data transfer object for AgingBucket
/// - `AgingBucketSummary` - Summary view of AgingBucket
/// - `AgingBucketId` - Type-safe ID wrapper
/// - `DunningRunDto` - Data transfer object for DunningRun
/// - `DunningRunSummary` - Summary view of DunningRun
/// - `DunningRunId` - Type-safe ID wrapper
/// - `DunningActionDto` - Data transfer object for DunningAction
/// - `DunningActionSummary` - Summary view of DunningAction
/// - `DunningActionId` - Type-safe ID wrapper
/// - `ModeOfPaymentDto` - Data transfer object for ModeOfPayment
/// - `ModeOfPaymentSummary` - Summary view of ModeOfPayment
/// - `ModeOfPaymentId` - Type-safe ID wrapper
/// - `PaymentEntryDto` - Data transfer object for PaymentEntry
/// - `PaymentEntrySummary` - Summary view of PaymentEntry
/// - `PaymentEntryId` - Type-safe ID wrapper
/// - `PaymentAllocationDto` - Data transfer object for PaymentAllocation
/// - `PaymentAllocationSummary` - Summary view of PaymentAllocation
/// - `PaymentAllocationId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PaymentQueryService` - Read-only queries
///
/// ## Public Events
/// - `AgingSnapshotCreatedEvent` - Published when AgingSnapshot is created
/// - `AgingSnapshotUpdatedEvent` - Published when AgingSnapshot is updated
/// - `AgingSnapshotDeletedEvent` - Published when AgingSnapshot is deleted
/// - `AgingBucketCreatedEvent` - Published when AgingBucket is created
/// - `AgingBucketUpdatedEvent` - Published when AgingBucket is updated
/// - `AgingBucketDeletedEvent` - Published when AgingBucket is deleted
/// - `DunningRunCreatedEvent` - Published when DunningRun is created
/// - `DunningRunUpdatedEvent` - Published when DunningRun is updated
/// - `DunningRunDeletedEvent` - Published when DunningRun is deleted
/// - `DunningActionCreatedEvent` - Published when DunningAction is created
/// - `DunningActionUpdatedEvent` - Published when DunningAction is updated
/// - `DunningActionDeletedEvent` - Published when DunningAction is deleted
/// - `ModeOfPaymentCreatedEvent` - Published when ModeOfPayment is created
/// - `ModeOfPaymentUpdatedEvent` - Published when ModeOfPayment is updated
/// - `ModeOfPaymentDeletedEvent` - Published when ModeOfPayment is deleted
/// - `PaymentEntryCreatedEvent` - Published when PaymentEntry is created
/// - `PaymentEntryUpdatedEvent` - Published when PaymentEntry is updated
/// - `PaymentEntryDeletedEvent` - Published when PaymentEntry is deleted
/// - `PaymentAllocationCreatedEvent` - Published when PaymentAllocation is created
/// - `PaymentAllocationUpdatedEvent` - Published when PaymentAllocation is updated
/// - `PaymentAllocationDeletedEvent` - Published when PaymentAllocation is deleted
pub struct ExportSummary;
