//! Payment Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Payment exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use payment::exports::{ModeOfPaymentDto, PaymentQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ModeOfPaymentDto` - Data transfer object for ModeOfPayment
/// - `ModeOfPaymentSummary` - Summary view of ModeOfPayment
/// - `ModeOfPaymentId` - Type-safe ID wrapper
/// - `PaymentEntryDto` - Data transfer object for PaymentEntry
/// - `PaymentEntrySummary` - Summary view of PaymentEntry
/// - `PaymentEntryId` - Type-safe ID wrapper
/// - `PaymentAllocationDto` - Data transfer object for PaymentAllocation
/// - `PaymentAllocationSummary` - Summary view of PaymentAllocation
/// - `PaymentAllocationId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PaymentQueryService` - Read-only queries
///
/// ## Public Events
/// - `ModeOfPaymentCreatedEvent` - Published when ModeOfPayment is created
/// - `ModeOfPaymentUpdatedEvent` - Published when ModeOfPayment is updated
/// - `ModeOfPaymentDeletedEvent` - Published when ModeOfPayment is deleted
/// - `PaymentEntryCreatedEvent` - Published when PaymentEntry is created
/// - `PaymentEntryUpdatedEvent` - Published when PaymentEntry is updated
/// - `PaymentEntryDeletedEvent` - Published when PaymentEntry is deleted
/// - `PaymentAllocationCreatedEvent` - Published when PaymentAllocation is created
/// - `PaymentAllocationUpdatedEvent` - Published when PaymentAllocation is updated
/// - `PaymentAllocationDeletedEvent` - Published when PaymentAllocation is deleted
pub struct ExportSummary;
