//! Public services for Payment module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Payment module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PaymentQueryService: Send + Sync {
    /// Get ModeOfPayment by ID
    async fn get_mode_of_payment(&self, id: ModeOfPaymentId) -> Result<Option<ModeOfPaymentDto>>;

    /// Get ModeOfPayment summary by ID
    async fn get_mode_of_payment_summary(&self, id: ModeOfPaymentId) -> Result<Option<ModeOfPaymentSummary>>;

    /// Check if ModeOfPayment exists
    async fn mode_of_payment_exists(&self, id: ModeOfPaymentId) -> Result<bool>;

    /// Get PaymentEntry by ID
    async fn get_payment_entry(&self, id: PaymentEntryId) -> Result<Option<PaymentEntryDto>>;

    /// Get PaymentEntry summary by ID
    async fn get_payment_entry_summary(&self, id: PaymentEntryId) -> Result<Option<PaymentEntrySummary>>;

    /// Check if PaymentEntry exists
    async fn payment_entry_exists(&self, id: PaymentEntryId) -> Result<bool>;

    /// Get PaymentAllocation by ID
    async fn get_payment_allocation(&self, id: PaymentAllocationId) -> Result<Option<PaymentAllocationDto>>;

    /// Get PaymentAllocation summary by ID
    async fn get_payment_allocation_summary(&self, id: PaymentAllocationId) -> Result<Option<PaymentAllocationSummary>>;

    /// Check if PaymentAllocation exists
    async fn payment_allocation_exists(&self, id: PaymentAllocationId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of PaymentQueryService
pub struct PaymentQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> PaymentQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
