//! Public types for Payment module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// AGINGSNAPSHOT TYPES
// ============================================================================

/// Type-safe ID for AgingSnapshot
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgingSnapshotId(pub Uuid);

impl AgingSnapshotId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AgingSnapshotId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AgingSnapshotId> for Uuid {
    fn from(id: AgingSnapshotId) -> Self {
        id.0
    }
}

/// Data transfer object for AgingSnapshot
///
/// This is the public representation of AgingSnapshot for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotDto {
    pub id: AgingSnapshotId,
    pub company_id: Uuid,
    pub as_of_date: NaiveDate,
    pub direction: String,
    pub total_outstanding: Decimal,
    pub bucket_current: Decimal,
    pub bucket_1_30: Decimal,
    pub bucket_31_60: Decimal,
    pub bucket_61_90: Decimal,
    pub bucket_90p: Decimal,
    pub status: SnapshotStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of AgingSnapshot for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotSummary {
    pub id: AgingSnapshotId,
    pub status: SnapshotStatus,
}

/// Reference to AgingSnapshot for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshotRef {
    pub id: AgingSnapshotId,
}

// ============================================================================
// AGINGBUCKET TYPES
// ============================================================================

/// Type-safe ID for AgingBucket
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgingBucketId(pub Uuid);

impl AgingBucketId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AgingBucketId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AgingBucketId> for Uuid {
    fn from(id: AgingBucketId) -> Self {
        id.0
    }
}

/// Data transfer object for AgingBucket
///
/// This is the public representation of AgingBucket for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketDto {
    pub id: AgingBucketId,
    pub company_id: Uuid,
    pub snapshot_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: String,
    pub party_id: Option<Uuid>,
    pub due_date: NaiveDate,
    pub days_past_due: i32,
    pub outstanding_amount: Decimal,
    pub bucket: AgingBucketName,
    pub metadata: serde_json::Value,
}

/// Summary view of AgingBucket for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketSummary {
    pub id: AgingBucketId,
}

/// Reference to AgingBucket for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingBucketRef {
    pub id: AgingBucketId,
}

// ============================================================================
// DUNNINGRUN TYPES
// ============================================================================

/// Type-safe ID for DunningRun
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DunningRunId(pub Uuid);

impl DunningRunId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DunningRunId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DunningRunId> for Uuid {
    fn from(id: DunningRunId) -> Self {
        id.0
    }
}

/// Data transfer object for DunningRun
///
/// This is the public representation of DunningRun for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunDto {
    pub id: DunningRunId,
    pub company_id: Uuid,
    pub as_of_date: NaiveDate,
    pub direction: String,
    pub snapshot_id: Option<Uuid>,
    pub actions_emitted: i32,
    pub status: DunningRunStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of DunningRun for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunSummary {
    pub id: DunningRunId,
    pub status: DunningRunStatus,
}

/// Reference to DunningRun for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningRunRef {
    pub id: DunningRunId,
}

// ============================================================================
// DUNNINGACTION TYPES
// ============================================================================

/// Type-safe ID for DunningAction
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DunningActionId(pub Uuid);

impl DunningActionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DunningActionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DunningActionId> for Uuid {
    fn from(id: DunningActionId) -> Self {
        id.0
    }
}

/// Data transfer object for DunningAction
///
/// This is the public representation of DunningAction for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionDto {
    pub id: DunningActionId,
    pub company_id: Uuid,
    pub run_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: String,
    pub party_id: Option<Uuid>,
    pub level: DunningLevel,
    pub action_type: DunningActionType,
    pub days_past_due: i32,
    pub outstanding_amount: Decimal,
    pub status: DunningActionStatus,
    pub processed_at: Option<DateTime<Utc>>,
    pub result_ref: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of DunningAction for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionSummary {
    pub id: DunningActionId,
    pub status: DunningActionStatus,
}

/// Reference to DunningAction for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningActionRef {
    pub id: DunningActionId,
}

// ============================================================================
// MODEOFPAYMENT TYPES
// ============================================================================

/// Type-safe ID for ModeOfPayment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ModeOfPaymentId(pub Uuid);

impl ModeOfPaymentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ModeOfPaymentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ModeOfPaymentId> for Uuid {
    fn from(id: ModeOfPaymentId) -> Self {
        id.0
    }
}

/// Data transfer object for ModeOfPayment
///
/// This is the public representation of ModeOfPayment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentDto {
    pub id: ModeOfPaymentId,
    pub code: String,
    pub name: String,
    pub mode_type: ModeType,
    pub default_account_id: Option<Uuid>,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of ModeOfPayment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentSummary {
    pub id: ModeOfPaymentId,
    pub name: String,
}

/// Reference to ModeOfPayment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeOfPaymentRef {
    pub id: ModeOfPaymentId,
}

// ============================================================================
// PAYMENTENTRY TYPES
// ============================================================================

/// Type-safe ID for PaymentEntry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentEntryId(pub Uuid);

impl PaymentEntryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentEntryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentEntryId> for Uuid {
    fn from(id: PaymentEntryId) -> Self {
        id.0
    }
}

/// Data transfer object for PaymentEntry
///
/// This is the public representation of PaymentEntry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntryDto {
    pub id: PaymentEntryId,
    pub payment_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub payment_type: PaymentType,
    pub party_type: Option<PaymentPartyType>,
    pub party_id: Option<Uuid>,
    pub posting_date: NaiveDate,
    pub currency: String,
    pub mode_of_payment_id: Option<Uuid>,
    pub paid_amount: Decimal,
    pub allocated_amount: Decimal,
    pub unallocated_amount: Decimal,
    pub bank_account_id: Uuid,
    pub party_account_id: Uuid,
    pub withholding_amount: Decimal,
    pub withholding_account_id: Option<Uuid>,
    pub withholding_tax_type: WithholdingTaxType,
    pub status: PaymentStatus,
    pub posting_state: GlPostingState,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub posted_at: Option<DateTime<Utc>>,
    pub reference_no: Option<String>,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of PaymentEntry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntrySummary {
    pub id: PaymentEntryId,
    pub status: PaymentStatus,
}

/// Reference to PaymentEntry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEntryRef {
    pub id: PaymentEntryId,
}

// ============================================================================
// PAYMENTALLOCATION TYPES
// ============================================================================

/// Type-safe ID for PaymentAllocation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentAllocationId(pub Uuid);

impl PaymentAllocationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentAllocationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentAllocationId> for Uuid {
    fn from(id: PaymentAllocationId) -> Self {
        id.0
    }
}

/// Data transfer object for PaymentAllocation
///
/// This is the public representation of PaymentAllocation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationDto {
    pub id: PaymentAllocationId,
    pub company_id: Uuid,
    pub payment_id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: SettlementKind,
    pub allocated_amount: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of PaymentAllocation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationSummary {
    pub id: PaymentAllocationId,
}

/// Reference to PaymentAllocation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentAllocationRef {
    pub id: PaymentAllocationId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
