//! Payment Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AgingSnapshotService;
pub use application::service::AgingBucketService;
pub use application::service::DunningRunService;
pub use application::service::DunningActionService;
pub use application::service::ModeOfPaymentService;
pub use application::service::PaymentEntryService;
pub use application::service::PaymentAllocationService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Payment module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let payment = PaymentModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = payment.all_crud_routes();
/// ```
pub struct PaymentModule {
    pub aging_snapshot_service: Arc<AgingSnapshotService>,
    pub aging_bucket_service: Arc<AgingBucketService>,
    pub dunning_run_service: Arc<DunningRunService>,
    pub dunning_action_service: Arc<DunningActionService>,
    pub mode_of_payment_service: Arc<ModeOfPaymentService>,
    pub payment_entry_service: Arc<PaymentEntryService>,
    pub payment_allocation_service: Arc<PaymentAllocationService>,
}

impl PaymentModule {
    /// Create a new module builder
    pub fn builder() -> PaymentModuleBuilder {
        PaymentModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_aging_snapshot_routes,
            create_aging_bucket_routes,
            create_dunning_run_routes,
            create_dunning_action_routes,
            create_mode_of_payment_routes,
            create_payment_entry_routes,
            create_payment_allocation_routes,
        };

        Router::new()
            .merge(create_aging_snapshot_routes(self.aging_snapshot_service.clone()))
            .merge(create_aging_bucket_routes(self.aging_bucket_service.clone()))
            .merge(create_dunning_run_routes(self.dunning_run_service.clone()))
            .merge(create_dunning_action_routes(self.dunning_action_service.clone()))
            .merge(create_mode_of_payment_routes(self.mode_of_payment_service.clone()))
            .merge(create_payment_entry_routes(self.payment_entry_service.clone()))
            .merge(create_payment_allocation_routes(self.payment_allocation_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for PaymentModule
pub struct PaymentModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PaymentModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PaymentModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // AgingSnapshot service
        let aging_snapshot_repository = Arc::new(AgingSnapshotRepository::new(db_pool.clone()));
        let aging_snapshot_service = Arc::new(AgingSnapshotService::with_repository(aging_snapshot_repository.clone()));

        // AgingBucket service
        let aging_bucket_repository = Arc::new(AgingBucketRepository::new(db_pool.clone()));
        let aging_bucket_service = Arc::new(AgingBucketService::with_repository(aging_bucket_repository.clone()));

        // DunningRun service
        let dunning_run_repository = Arc::new(DunningRunRepository::new(db_pool.clone()));
        let dunning_run_service = Arc::new(DunningRunService::with_repository(dunning_run_repository.clone()));

        // DunningAction service
        let dunning_action_repository = Arc::new(DunningActionRepository::new(db_pool.clone()));
        let dunning_action_service = Arc::new(DunningActionService::with_repository(dunning_action_repository.clone()));

        // ModeOfPayment service
        let mode_of_payment_repository = Arc::new(ModeOfPaymentRepository::new(db_pool.clone()));
        let mode_of_payment_service = Arc::new(ModeOfPaymentService::with_repository(mode_of_payment_repository.clone()));

        // PaymentEntry service
        let payment_entry_repository = Arc::new(PaymentEntryRepository::new(db_pool.clone()));
        let payment_entry_service = Arc::new(PaymentEntryService::with_repository(payment_entry_repository.clone()));

        // PaymentAllocation service
        let payment_allocation_repository = Arc::new(PaymentAllocationRepository::new(db_pool.clone()));
        let payment_allocation_service = Arc::new(PaymentAllocationService::with_repository(payment_allocation_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(PaymentModule {
            aging_snapshot_service,
            aging_bucket_service,
            dunning_run_service,
            dunning_action_service,
            mode_of_payment_service,
            payment_entry_service,
            payment_allocation_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PaymentModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
