//! Use case type aliases for AgingSnapshot aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAgingSnapshotDto, UpdateAgingSnapshotDto};
use crate::application::service::AgingSnapshotService;
use crate::domain::entity::AgingSnapshot;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAgingSnapshotUseCase = CreateUseCase<AgingSnapshot, CreateAgingSnapshotDto, AgingSnapshotService>;
pub type UpdateAgingSnapshotUseCase = UpdateUseCase<AgingSnapshot, UpdateAgingSnapshotDto, AgingSnapshotService>;
pub type GetAgingSnapshotUseCase    = GetUseCase<AgingSnapshot, AgingSnapshotService>;
pub type DeleteAgingSnapshotUseCase = DeleteUseCase<AgingSnapshot, AgingSnapshotService>;
pub type ListAgingSnapshotUseCase   = ListUseCase<AgingSnapshot, AgingSnapshotService>;

// <<< CUSTOM
// END CUSTOM
