//! Use case type aliases for AgingBucket aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAgingBucketDto, UpdateAgingBucketDto};
use crate::application::service::AgingBucketService;
use crate::domain::entity::AgingBucket;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAgingBucketUseCase = CreateUseCase<AgingBucket, CreateAgingBucketDto, AgingBucketService>;
pub type UpdateAgingBucketUseCase = UpdateUseCase<AgingBucket, UpdateAgingBucketDto, AgingBucketService>;
pub type GetAgingBucketUseCase    = GetUseCase<AgingBucket, AgingBucketService>;
pub type DeleteAgingBucketUseCase = DeleteUseCase<AgingBucket, AgingBucketService>;
pub type ListAgingBucketUseCase   = ListUseCase<AgingBucket, AgingBucketService>;

// <<< CUSTOM
// END CUSTOM
