//! Use case type aliases for DunningRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDunningRunDto, UpdateDunningRunDto};
use crate::application::service::DunningRunService;
use crate::domain::entity::DunningRun;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDunningRunUseCase = CreateUseCase<DunningRun, CreateDunningRunDto, DunningRunService>;
pub type UpdateDunningRunUseCase = UpdateUseCase<DunningRun, UpdateDunningRunDto, DunningRunService>;
pub type GetDunningRunUseCase    = GetUseCase<DunningRun, DunningRunService>;
pub type DeleteDunningRunUseCase = DeleteUseCase<DunningRun, DunningRunService>;
pub type ListDunningRunUseCase   = ListUseCase<DunningRun, DunningRunService>;

// <<< CUSTOM
// END CUSTOM
