//! Use case type aliases for DunningAction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDunningActionDto, UpdateDunningActionDto};
use crate::application::service::DunningActionService;
use crate::domain::entity::DunningAction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDunningActionUseCase = CreateUseCase<DunningAction, CreateDunningActionDto, DunningActionService>;
pub type UpdateDunningActionUseCase = UpdateUseCase<DunningAction, UpdateDunningActionDto, DunningActionService>;
pub type GetDunningActionUseCase    = GetUseCase<DunningAction, DunningActionService>;
pub type DeleteDunningActionUseCase = DeleteUseCase<DunningAction, DunningActionService>;
pub type ListDunningActionUseCase   = ListUseCase<DunningAction, DunningActionService>;

// <<< CUSTOM
// END CUSTOM
