//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod mode_of_payment_usecases;
pub mod payment_entry_usecases;
pub mod payment_allocation_usecases;

pub use mode_of_payment_usecases::{
    CreateModeOfPaymentUseCase, UpdateModeOfPaymentUseCase, GetModeOfPaymentUseCase,
    DeleteModeOfPaymentUseCase, ListModeOfPaymentUseCase,
};
pub use payment_entry_usecases::{
    CreatePaymentEntryUseCase, UpdatePaymentEntryUseCase, GetPaymentEntryUseCase,
    DeletePaymentEntryUseCase, ListPaymentEntryUseCase,
};
pub use payment_allocation_usecases::{
    CreatePaymentAllocationUseCase, UpdatePaymentAllocationUseCase, GetPaymentAllocationUseCase,
    DeletePaymentAllocationUseCase, ListPaymentAllocationUseCase,
};

// <<< CUSTOM
// END CUSTOM
