//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod aging_snapshot_usecases;
pub mod aging_bucket_usecases;
pub mod dunning_run_usecases;
pub mod dunning_action_usecases;
pub mod mode_of_payment_usecases;
pub mod payment_entry_usecases;
pub mod payment_allocation_usecases;

pub use aging_snapshot_usecases::{
    CreateAgingSnapshotUseCase, UpdateAgingSnapshotUseCase, GetAgingSnapshotUseCase,
    DeleteAgingSnapshotUseCase, ListAgingSnapshotUseCase,
};
pub use aging_bucket_usecases::{
    CreateAgingBucketUseCase, UpdateAgingBucketUseCase, GetAgingBucketUseCase,
    DeleteAgingBucketUseCase, ListAgingBucketUseCase,
};
pub use dunning_run_usecases::{
    CreateDunningRunUseCase, UpdateDunningRunUseCase, GetDunningRunUseCase,
    DeleteDunningRunUseCase, ListDunningRunUseCase,
};
pub use dunning_action_usecases::{
    CreateDunningActionUseCase, UpdateDunningActionUseCase, GetDunningActionUseCase,
    DeleteDunningActionUseCase, ListDunningActionUseCase,
};
pub use mode_of_payment_usecases::{
    CreateModeOfPaymentUseCase, UpdateModeOfPaymentUseCase, GetModeOfPaymentUseCase,
    DeleteModeOfPaymentUseCase, ListModeOfPaymentUseCase,
};
pub use payment_entry_usecases::{
    CreatePaymentEntryUseCase, UpdatePaymentEntryUseCase, GetPaymentEntryUseCase,
    DeletePaymentEntryUseCase, ListPaymentEntryUseCase,
};
pub use payment_allocation_usecases::{
    CreatePaymentAllocationUseCase, UpdatePaymentAllocationUseCase, GetPaymentAllocationUseCase,
    DeletePaymentAllocationUseCase, ListPaymentAllocationUseCase,
};

// <<< CUSTOM
// END CUSTOM
