//! Use case type aliases for ModeOfPayment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateModeOfPaymentDto, UpdateModeOfPaymentDto};
use crate::application::service::ModeOfPaymentService;
use crate::domain::entity::ModeOfPayment;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateModeOfPaymentUseCase = CreateUseCase<ModeOfPayment, CreateModeOfPaymentDto, ModeOfPaymentService>;
pub type UpdateModeOfPaymentUseCase = UpdateUseCase<ModeOfPayment, UpdateModeOfPaymentDto, ModeOfPaymentService>;
pub type GetModeOfPaymentUseCase    = GetUseCase<ModeOfPayment, ModeOfPaymentService>;
pub type DeleteModeOfPaymentUseCase = DeleteUseCase<ModeOfPayment, ModeOfPaymentService>;
pub type ListModeOfPaymentUseCase   = ListUseCase<ModeOfPayment, ModeOfPaymentService>;

// <<< CUSTOM
// END CUSTOM
