//! Use case type aliases for PaymentEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePaymentEntryDto, UpdatePaymentEntryDto};
use crate::application::service::PaymentEntryService;
use crate::domain::entity::PaymentEntry;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePaymentEntryUseCase = CreateUseCase<PaymentEntry, CreatePaymentEntryDto, PaymentEntryService>;
pub type UpdatePaymentEntryUseCase = UpdateUseCase<PaymentEntry, UpdatePaymentEntryDto, PaymentEntryService>;
pub type GetPaymentEntryUseCase    = GetUseCase<PaymentEntry, PaymentEntryService>;
pub type DeletePaymentEntryUseCase = DeleteUseCase<PaymentEntry, PaymentEntryService>;
pub type ListPaymentEntryUseCase   = ListUseCase<PaymentEntry, PaymentEntryService>;

// <<< CUSTOM
// END CUSTOM
