//! Use case type aliases for PaymentAllocation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePaymentAllocationDto, UpdatePaymentAllocationDto};
use crate::application::service::PaymentAllocationService;
use crate::domain::entity::PaymentAllocation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePaymentAllocationUseCase = CreateUseCase<PaymentAllocation, CreatePaymentAllocationDto, PaymentAllocationService>;
pub type UpdatePaymentAllocationUseCase = UpdateUseCase<PaymentAllocation, UpdatePaymentAllocationDto, PaymentAllocationService>;
pub type GetPaymentAllocationUseCase    = GetUseCase<PaymentAllocation, PaymentAllocationService>;
pub type DeletePaymentAllocationUseCase = DeleteUseCase<PaymentAllocation, PaymentAllocationService>;
pub type ListPaymentAllocationUseCase   = ListUseCase<PaymentAllocation, PaymentAllocationService>;

// <<< CUSTOM
// END CUSTOM
