//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod mode_of_payment_handler;
pub mod payment_entry_handler;
pub mod payment_allocation_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use mode_of_payment_handler::{create_mode_of_payment_routes, create_mode_of_payment_read_routes, create_mode_of_payment_write_routes};
pub use payment_entry_handler::{create_payment_entry_routes, create_payment_entry_read_routes, create_payment_entry_write_routes};
pub use payment_allocation_handler::{create_payment_allocation_routes, create_payment_allocation_read_routes, create_payment_allocation_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_payment_routes;
// END CUSTOM